---
title: "Testing"
output:
  pdf_document: 
    toc: true
    fig_caption: yes
header-includes:
  - \usepackage{amsmath}
---
\newpage

```{r library_setup, results=FALSE, warning=FALSE, message=FALSE, echo=FALSE}
rm(list=ls())
require(tinytex) #LaTeX
require(ggplot2) #plots
require(AEC) #JP-Renne functions
require(expm) #matrix exponents
require(here) #directory finder
require(stringr) # ?
require(dplyr) #data management
require(lubridate) #data dates management

getwd()
setwd("...")
```

# Data 

## Raw Data
```{r rawdata_setup, results=FALSE, warning=FALSE, message=FALSE}

#political shocks
raw_truths <- read.csv(here("data/political_data", "trump_all_truths.csv"))
raw_tweets <- read.csv(here("data/political_data", "tweets.csv"))


#market prices
raw_ONEQ <- read.csv(here("data/market_data", "ONEQ.csv"))
raw_SMI <- read.csv(here("data/market_data", "SMI.csv"))
raw_SPY <- read.csv(here("data/market_data", "SPY.csv")) 
raw_VTHR <- read.csv(here("data/market_data", "VTHR.csv"))
raw_VTI <- read.csv(here("data/market_data", "VTI.csv"))
raw_VGK <- read.csv(here("data/market_data", "VGK.csv"))
raw_DAX <- read.csv(here("data/market_data", "DAX.csv"))
raw_ASHR <- read.csv(here("data/market_data", "ASHR.csv"))

raw_SPYy <- read.csv(here("data/market_data", "Spyqyahoo.csv")) #yahoo

```

## Cleaning The Data
```{r cleandata_setup, results=FALSE, warning=FALSE, message=FALSE}

#political shocks
truths <- 1
tweets <- 1


#market prices #only cleaning dates for the time being
raw_ONEQ$timestamp = as.POSIXct(raw_ONEQ$timestamp, format = "%Y-%m-%d %H:%M:%S", tz = "EST")
raw_SMI$timestamp = as.POSIXct(raw_SMI$timestamp, format = "%Y-%m-%d %H:%M:%S", tz = "EST")
raw_SPY$timestamp = as.POSIXct(raw_SPY$timestamp, format = "%Y-%m-%d %H:%M:%S", tz = "EST")
raw_VTHR$timestamp = as.POSIXct(raw_VTHR$timestamp, format = "%Y-%m-%d %H:%M:%S", tz = "EST")
raw_VTI$timestamp = as.POSIXct(raw_VTI$timestamp, format = "%Y-%m-%d %H:%M:%S", tz = "EST")
raw_VGK$timestamp = as.POSIXct(raw_VGK$timestamp, format = "%Y-%m-%d %H:%M:%S", tz = "UCT")
raw_DAX$timestamp = as.POSIXct(raw_DAX$timestamp, format = "%Y-%m-%d %H:%M:%S", tz = "UCT")
raw_ASHR$timestamp = as.POSIXct(raw_ASHR$timestamp, format = "%Y-%m-%d %H:%M:%S", tz = "UCT") #fix timezone

```

## Daily Data
```{r dailydata, results=FALSE, warning=FALSE, message=FALSE}

#political shocks


#market prices
day_SPY_0409 = filter(raw_SPY, str_detect(timestamp, "^2025-04-09")) #9th of april
day_SPY_0409$timestamp = as.POSIXct(day_SPY_0409$timestamp, 
                                    format = "%Y-%m-%d %H:%M:%S", tz = "EST")

yahoo_ds0409 = filter(raw_SPYy, str_detect(Date, "^2025-04-09"))
yahoo_ds0409$Date = as.POSIXct(yahoo_ds0409$Date, 
                                    format = "%Y-%m-%dT%H:%M:%S", tz = "UTC")
yahoo_ds0409$Date = with_tz(yahoo_ds0409$Date, "EST")

```


# Plots

## Total 
```{r total market plots}

#SPY
ggplot(raw_SPY, aes(x = timestamp, y = close)) +
  geom_point(color = "blue", size = 0.01) +
  geom_line(aes(group=1), color="blue", linewidth=0.05) +
  labs(title = "SPY Price Over Time",
       x = "Time",
       y = "Close Price") 




#ONEQ
ggplot(raw_ONEQ, aes(x = timestamp, y = close)) +
  geom_point(color = "blue", size = 0.01) +
  geom_line(aes(group=1), color="blue", linewidth=0.05) +
  labs(title = "ONEQ Price Over Time",
       x = "Time",
       y = "Close Price") +
   scale_x_datetime(date_labels = "%b:%d",  
                    date_breaks = "2 day") +
   theme_minimal() +
   theme(axis.text.x = element_text(angle = 45, hjust = 1))
   


#SMI
ggplot(raw_SMI, aes(x = timestamp, y = close)) +
  geom_point(color = "blue", size = 0.01) +
  geom_line(aes(group=1), color="blue", linewidth=0.05) +
  labs(title = "SMI Price Over Time",
       x = "Time",
       y = "Close Price") +
   scale_x_datetime(date_labels = "%b:%d",  
                    date_breaks = "2 day") +
   theme_minimal() +
   theme(axis.text.x = element_text(angle = 45, hjust = 1))
   




#VTHR
ggplot(raw_VTHR, aes(x = timestamp, y = close)) +
  geom_point(color = "blue", size = 0.01) +
  geom_line(aes(group=1), color="blue", linewidth=0.05) +
  labs(title = "VTHR Price Over Time",
       x = "Time",
       y = "Close Price") +
   scale_x_datetime(date_labels = "%b:%d",  
                    date_breaks = "2 day") +
   theme_minimal() +
   theme(axis.text.x = element_text(angle = 45, hjust = 1))
   


#VTI
ggplot(raw_VTI, aes(x = timestamp, y = close)) +
  geom_point(color = "blue", size = 0.01) +
  geom_line(aes(group=1), color="blue", linewidth=0.05) +
  labs(title = "VTI Price Over Time",
       x = "Time",
       y = "Close Price") +
   scale_x_datetime(date_labels = "%b:%d",  
                    date_breaks = "2 day") +
   theme_minimal() +
   theme(axis.text.x = element_text(angle = 45, hjust = 1))
   

   
#VGK
ggplot(raw_VGK, aes(x = timestamp, y = close)) +
  geom_point(color = "blue", size = 0.01) +
  geom_line(aes(group=1), color="blue", linewidth=0.05) +
  labs(title = "VGK Price Over Time",
       x = "Time",
       y = "Close Price") +
   scale_x_datetime(date_labels = "%b:%d",  
                    date_breaks = "2 day") +
   theme_minimal() +
   theme(axis.text.x = element_text(angle = 45, hjust = 1))
   
   
#DAX
ggplot(raw_DAX, aes(x = timestamp, y = close)) +
  geom_point(color = "blue", size = 0.01) +
  geom_line(aes(group=1), color="blue", linewidth=0.05) +
  labs(title = "DAX Price Over Time",
       x = "Time",
       y = "Close Price") +
   scale_x_datetime(date_labels = "%b:%d",  
                    date_breaks = "2 day") +
   theme_minimal() +
   theme(axis.text.x = element_text(angle = 45, hjust = 1))


#ASHR
ggplot(raw_ASHR, aes(x = timestamp, y = close)) +
  geom_point(color = "blue", size = 0.01) +
  geom_line(aes(group=1), color="blue", linewidth=0.05) +
  labs(title = "ASHR Price Over Time",
       x = "Time",
       y = "Close Price") +
   scale_x_datetime(date_labels = "%b:%d",  
                    date_breaks = "2 day") +
   theme_minimal() +
   theme(axis.text.x = element_text(angle = 45, hjust = 1))

```


## Per Day
```{r daily market plots}

#SPY Source: alpha
ggplot(day_SPY_0409, aes(x = timestamp, y = close)) +
  geom_point(color = "blue", size = 0.01) +
  geom_line(aes(group=1)) +
  labs(title = "SPY alpha Price April 9th",
       x = "Time",
       y = "Close Price") +
   scale_x_datetime(date_labels = "%H:%M",  
                    date_breaks = "60 min") +
   theme_minimal() +
   theme(axis.text.x = element_text(angle = 45, hjust = 1))


#SPY log prices Source: alpha
ggplot(day_SPY_0409, aes(x = timestamp, y = log(close))) +
  geom_point(color = "blue", size = 0.01) +
  geom_line(aes(group=1)) +
  labs(title = "SPY Log Price April 9th",
       x = "Time",
       y = "Log Close Price") +
   scale_x_datetime(date_labels = "%H:%M",  
                    date_breaks = "60 min") +
   theme_minimal() +
   theme(axis.text.x = element_text(angle = 45, hjust = 1))


#SPY Source: yahoo
ggplot(yahoo_ds0409, aes(x = Date, y = Close)) +
  geom_point(color = "blue", size = 0.01) +
  geom_line(aes(group=1)) +
  labs(title = "SPY yahoo Price April 9th",
       x = "Time",
       y = "Close Price") +
   scale_x_datetime(date_labels = "%H:%M",  
                    date_breaks = "60 min") +
   theme_minimal() +
   theme(axis.text.x = element_text(angle = 45, hjust = 1))



```

# Time Series Analysis
```{r time series}

acf(log(day_SPY_0409$close))
pacf(log(day_SPY_0409$close))

acf(log(raw_SPY$close))
pacf(log(raw_SPY$close))

```

Looks like an AR(1) process. ACF looks a bit odd though, all equal to 1?




































