---
title: "VAR Analysis"
output:
  pdf_document: 
    toc: true
    fig_caption: yes
    latex_engine: lualatex
header-includes:
  - \usepackage{amsmath}
---
\newpage

```{r library_setup, results=FALSE, warning=FALSE, message=FALSE, echo=FALSE}
rm(list=ls())
require(tinytex) #LaTeX
require(ggplot2) #plots
require(AEC) #JP-Renne functions
require(AER) #NW formula
require(forecast) #time series stuff
require(expm) #matrix exponents
require(here) #directory finder
require(stringr) # analysis of strings, important for the detection in tweets
require(dplyr) #data management
require(lubridate) #data dates management
require(zoo) #for lagging
require(jtools) #tables
require(huxtable) #tables
require(lmtest) #reg tests
require(vroom) #for loading data
require(data.table) #for data filtering
require(sysid) #for ARMA-X modeling
require(sandwhich) #regression errors
require(stargazer) #nice reg tables
require(tidytext) #text mining
require(textstem) #lemmatization
require(quanteda) #tokenization
require(texreg) #arima tables
require(vars) #VAR models
require(xts) #time series objects
require(tseries) #includes adf test
require(quantmod)
require(TSA)
require(aTSA)
require(tibble)
require(FinTS)
require(kableExtra)
require(writexl)
require(purrr)

getwd()
#setwd("...") -> set wd at base repo folder

#load helper functions
source(here("helperfunctions/data_loaders.R"))
source(here("helperfunctions/date_selector.R"))
source(here("helperfunctions/plotters.R"))
source(here("helperfunctions/quick_arma.R"))
source(here("helperfunctions/r.vol_calculators.R"))
source(here("helperfunctions/truths_cleaning_function.R"))
source(here("helperfunctions/armax_functions.R"))

```

```{r datasetup, results=FALSE, warning=FALSE, message=FALSE, echo=FALSE}

#load final dataset
source(here("helperfunctions/full_data.R"))

#select timeframe 
Vdata = filter(data,between(timestamp, as.Date('2014-01-01'), as.Date('2025-05-07')))

```


# VAR Models



## Volatility & Tariff Mention

```{r tariff}

y3 = cbind(Vdata$tariff, Vdata$SPY_vol)
colnames(y3)[1:2] <- c("tariff", "vol")
est.VAR3 <- VAR(y3,p=6)
table = summary(est.VAR3)
Omega3 <- var(residuals(est.VAR3))


screenreg(est.VAR3, digits = 6)


```

```{r B mat3}

#make the B matrix
loss3 <- function(param3){
  #Define the restriction
  B3 <- matrix(c(param3[1], param3[2], 0, param3[3]), ncol = 2)
  
  #Make BB' approximatively equal to omega
  X3 <- Omega3 - B3 %*% t(B3)
  
  #loss function
  loss3 <- sum(X3^2)
  return(loss3)
}

res.opt3 <- optim(c(1, 0, 1), loss3, method = "BFGS")
B.hat3 <- matrix(c(res.opt3$par[1], res.opt3$par[2], 0, res.opt3$par[3]), ncol = 2)

print(cbind(Omega3,B.hat3 %*% t(B.hat3)))

#shock by tariff
B.hat3

```



```{r IRF tariff}

#OLD
#get back the coefficient of est.VAR
phi3 <- Acoef(est.VAR3)
PHI3 = make.PHI(phi3)

#take the constant
constant3 <- sapply(est.VAR3$varresult, function(eq) coef(eq)["const"])
c3=as.matrix(constant3)

#Simulate the IRF
p3 <- length(phi3)
n3 <- dim(phi3[[1]])[1]

par(mfrow=c(2,2))
Y3 <- simul.VAR(c=c3, Phi = phi3, B = B.hat3, nb.sim ,y0.star=rep(0, n3*p3),
                indic.IRF = 1, u.shock = c(1,0))
par(mfrow=c(1,1))  
par(plt=c(0.1, 0.9, 0.1, 0.9))
plot(Y3[,2],type="l",lwd=2,xlab="",ylab="",main="Effect of XXX on XXX")



#NEW
irf_res <- irf(est.VAR3, impulse = "tariff", response = "vol", 
                  n.ahead = 7 * 5, boot = TRUE, ci = 0.95)

plot(irf_result)

single_varirf <- extract_varirf(irf_res)

single_varirf %>% 
  ggplot(aes(x=period, y=irf_tariff_vol, ymin=lower_tariff_vol, ymax=upper_tariff_vol)) +
  geom_hline(yintercept = 0, color="red") +
  geom_ribbon(fill="grey", alpha=0.2) +
  geom_line() +
  theme_light() +
  ggtitle("Orthogonal impulse response, asylum - asylum")+
  ylab("log(total asylum flow)")+
  xlab("") +
  theme_minimal()

```

```{r does vol granger cause tarrif}

#does volatility Granger cause tariff mentions
grangertest(y3[,c("vol","tariff")], order = 6)

#does tariff mentions Granger cause volatility
grangertest(y3[,c("tariff", "vol")], order = 6)

```


```{r}
extract_varirf <- function(...){
    
    varirf_object <- list(...) #list one or more varirf input objects
    
    get_vec_length <- function(list_item){nrow(list_item[[1]][[1]])}
    
    if (!("varirf" %in% mapply(class, varirf_object))){
        stop("this function only accepts 'varirf' class objects")
    }
    
    if (length(unique(mapply(class, varirf_object)))!=1){
        stop("all input items must be 'varirf' class objects")
    }    
    if (length(unique(mapply(get_vec_length, varirf_object)))!=1){
        stop("all irf vectors must have the same length")   
    }  
    
    period <- as.data.frame(0:(nrow(varirf_object[[1]][[1]][[1]])-1)) 
    names(period) <- "period"
    
    for (l in 1:length(varirf_object)){
        for (i in 1:3){
            for (j in 1:dim(varirf_object[[l]][[i]][[1]])[2]){
                for (k in 1:length(varirf_object[[l]][[1]])){
                    temp_colname <- paste(names(varirf_object[[l]][i]), #vector type (irf, lower, or upper)
                                          names(varirf_object[[l]][[i]])[k], #impulse name
                                          colnames(varirf_object[[l]][[i]][[k]])[j], #response name
                                          sep = "_")
                    
                    temp <- as.data.frame(varirf_object[[l]][[i]][[k]][, j]) #extracts the vector
                    
                    names(temp) <- temp_colname #add the column name (vectortype_impulse_reponse)
                    period <- cbind(period, temp) 
                }
                
            }
        }
    }
    names(period) <- tolower(names(period))
    return(period)
}
```

