---
title: "TRUE_SPY_VAR"
author: "pte"
date: "2025-05-14"
output: html_document
---

#SPY Volatility

```{r load packages}
library("quantmod")
library("TSA")
library("aTSA")
library("rugarch")
library("rmgarch")
library("ggplot2")
library("tibble")
library("dplyr")
library("lubridate")
library(tibble)
library(tidyverse)
library(knitr)
library("fGarch")
library(FinTS)
library(kableExtra)
library(writexl)
library(texreg)
library("purrr")
library("forecast")
require(tinytex) #LaTeX
require(ggplot2) #plots
require(AEC) #JP-Renne functions
require(AER) #NW formula
require(forecast) #time series stuff
require(expm) #matrix exponents
require(here) #directory finder
require(stringr) # analysis of strings, important for the detection in tweets
require(dplyr) #data management
require(lubridate) #data dates management
require(zoo) #for lagging
require(jtools) #tables
require(huxtable) #tables
require(lmtest) #reg tests
require(vroom) #for loading data
require(data.table) #for data filtering
require(sysid) #for ARMA-X modeling
require(sandwhich) #regression errors
require(stargazer) #nice reg tables
require(tidytext) #text mining
require(textstem) #lemmatization
require(quanteda) #tokenizationc vfv 
require(vars)



require(tinytex) #LaTeX
require(ggplot2) #plots
require(AEC) #JP-Renne functions
require(AER) #NW formula
require(forecast) #time series stuff
require(expm) #matrix exponents
require(here) #directory finder
require(stringr) # analysis of strings, important for the detection in tweets
require(dplyr) #data management
require(lubridate) #data dates management
require(zoo) #for lagging
require(jtools) #tables
require(huxtable) #tables
require(lmtest) #reg tests
require(vroom) #for loading data
require(data.table) #for data filtering
require(sysid) #for ARMA-X modeling
require(sandwhich) #regression errors
require(stargazer) #nice reg tables
require(tidytext) #text mining
require(textstem) #lemmatization
require(quanteda) #tokenization
require(syuzhet) #sentiment analysis
require(alphavantager)
require(tseries)

rm(list=ls())


#load helper functions
source(here("helperfunctions/data_loaders.R"))
source(here("helperfunctions/date_selector.R"))
source(here("helperfunctions/plotters.R"))
source(here("helperfunctions/quick_arma.R"))
source(here("helperfunctions/r.vol_calculators.R"))
source(here("helperfunctions/truths_cleaning_function.R"))
source(here("helperfunctions/armax_functions.R"))

```

```{r load data}
# Data 


## Load Base Data

# 1. Load Political Social Media

#contains posts from Twitter & TruthSocial
social <- read.csv(here("data/mothership", "social.csv"))

social_hourly <- read.csv(here("data/mothership", "socialhourly.csv"))


# 2. Load Financial

#S&P500
SPY <- read.csv(here("data/mothership", "SPY.csv"))

#STOXX50
VGK <- read.csv(here("data/mothership", "VGK.csv"))

#CSI 300 (China)
ASHR <- read.csv(here("data/mothership", "ASHR.CSV"))




#make posixct
SPY$timestamp = as.POSIXct(SPY$timestamp,format = "%Y-%m-%d %H:%M:%S")
VGK$timestamp = as.POSIXct(VGK$timestamp,format = "%Y-%m-%d %H:%M:%S")
ASHR$timestamp = as.POSIXct(ASHR$timestamp,format = "%Y-%m-%d %H:%M:%S")
social$timestamp = as.POSIXct(social$timestamp,format = "%Y-%m-%d %H:%M:%S")
social_hourly$timestamp = as.POSIXct(social_hourly$timestamp,format = "%Y-%m-%d %H:%M:%S")
social_hourly$adjusted_time = as.POSIXct(social_hourly$adjusted_time,format = "%Y-%m-%d %H:%M:%S")

#select timeframe 
SPY = filter(SPY,between(timestamp, as.Date('2014-01-01'), as.Date('2025-05-07')))
VGK = filter(VGK,between(timestamp, as.Date('2014-01-01'), as.Date('2025-05-07')))
ASHR = filter(ASHR,between(timestamp, as.Date('2014-01-01'), as.Date('2025-05-07')))
social = filter(social,between(timestamp, as.Date('2014-01-01'), as.Date('2025-05-07')))
social_hourly = filter(social_hourly,between(timestamp, as.Date('2014-01-01'), as.Date('2025-05-07')))
#SPY = filter(SPY,between(timestamp, as.Date('2018-01-01'), as.Date('2025-05-07')))
#VGK = filter(VGK,between(timestamp, as.Date('2018-01-01'), as.Date('2025-05-07')))
#ASHR = filter(ASHR,between(timestamp, as.Date('2018-01-01'), as.Date('2025-05-07')))
#social = filter(social,between(timestamp, as.Date('2018-01-01'), as.Date('2025-05-07')))
#social_hourly = filter(social_hourly,between(timestamp, as.Date('2018-01-01'), as.Date('2025-05-07')))





## Volatility

#find hourly volatility
SPY_volatility = dplyr::select(SPY,timestamp,r_vol_h)

#aggregating per hour
SPY_volatility = SPY_volatility %>%
  mutate(timestamp = floor_date(timestamp, unit = "hour")) %>%
  distinct(timestamp, .keep_all = TRUE) 





#find hourly volatility
VGK_volatility = dplyr::select(VGK,timestamp,r_vol_h)

#aggregating per hour
VGK_volatility = VGK_volatility %>%
  mutate(timestamp = floor_date(timestamp, unit = "hour")) %>%
  distinct(timestamp, .keep_all = TRUE) 



#find hourly volatility
ASHR_volatility = dplyr::select(ASHR,timestamp,r_vol_h)

#aggregating per hour
ASHR_volatility = ASHR_volatility %>%
  mutate(timestamp = floor_date(timestamp, unit = "hour")) %>%
  distinct(timestamp, .keep_all = TRUE) 







#Find tweet variables

## Number of Posts 
#find count
tweetcount = dplyr::select(social_hourly,timestamp,adjusted_time,N)

#for taking count of closed market hours
tweetcount2 <- tweetcount %>%
  group_by(adjusted_time) %>%
  summarise(N = sum(N)) 



# Data 


## Load Base Data

# 1. Load Political Social Media

#contains posts from Twitter & TruthSocial
social <- read.csv(here("data/mothership", "social.csv"))

social_hourly <- read.csv(here("data/mothership", "socialhourly.csv"))


# 2. Load Financial

#S&P500
SPY <- read.csv(here("data/mothership", "SPY.csv"))

#STOXX50
VGK <- read.csv(here("data/mothership", "VGK.csv"))

#CSI 300 (China)
ASHR <- read.csv(here("data/mothership", "ASHR.CSV"))




#make posixct
SPY$timestamp = as.POSIXct(SPY$timestamp,format = "%Y-%m-%d %H:%M:%S")
VGK$timestamp = as.POSIXct(VGK$timestamp,format = "%Y-%m-%d %H:%M:%S")
ASHR$timestamp = as.POSIXct(ASHR$timestamp,format = "%Y-%m-%d %H:%M:%S")
social$timestamp = as.POSIXct(social$timestamp,format = "%Y-%m-%d %H:%M:%S")
social_hourly$timestamp = as.POSIXct(social_hourly$timestamp,format = "%Y-%m-%d %H:%M:%S")
social_hourly$adjusted_time = as.POSIXct(social_hourly$adjusted_time,format = "%Y-%m-%d %H:%M:%S")

#select timeframe 
SPY = filter(SPY,between(timestamp, as.Date('2014-01-01'), as.Date('2025-05-07')))
VGK = filter(VGK,between(timestamp, as.Date('2014-01-01'), as.Date('2025-05-07')))
ASHR = filter(ASHR,between(timestamp, as.Date('2014-01-01'), as.Date('2025-05-07')))
social = filter(social,between(timestamp, as.Date('2014-01-01'), as.Date('2025-05-07')))
social_hourly = filter(social_hourly,between(timestamp, as.Date('2014-01-01'), as.Date('2025-05-07')))
#SPY = filter(SPY,between(timestamp, as.Date('2018-01-01'), as.Date('2025-05-07')))
#VGK = filter(VGK,between(timestamp, as.Date('2018-01-01'), as.Date('2025-05-07')))
#ASHR = filter(ASHR,between(timestamp, as.Date('2018-01-01'), as.Date('2025-05-07')))
#social = filter(social,between(timestamp, as.Date('2018-01-01'), as.Date('2025-05-07')))
#social_hourly = filter(social_hourly,between(timestamp, as.Date('2018-01-01'), as.Date('2025-05-07')))





## Volatility

#find hourly volatility
SPY_volatility = dplyr::select(SPY,timestamp,r_vol_h)

#aggregating per hour
SPY_volatility = SPY_volatility %>%
  mutate(timestamp = floor_date(timestamp, unit = "hour")) %>%
  distinct(timestamp, .keep_all = TRUE) 

#plot
hvol_plotter(SPY_volatility,breaks="3 month", 
             title="Realised Volatility - SPY")




#find hourly volatility
VGK_volatility = dplyr::select(VGK,timestamp,r_vol_h)

#aggregating per hour
VGK_volatility = VGK_volatility %>%
  mutate(timestamp = floor_date(timestamp, unit = "hour")) %>%
  distinct(timestamp, .keep_all = TRUE) 



#find hourly volatility
ASHR_volatility = dplyr::select(ASHR,timestamp,r_vol_h)

#aggregating per hour
ASHR_volatility = ASHR_volatility %>%
  mutate(timestamp = floor_date(timestamp, unit = "hour")) %>%
  distinct(timestamp, .keep_all = TRUE) 







#Find tweet variables

## Number of Posts 
#find count
tweetcount = dplyr::select(social_hourly,timestamp,adjusted_time,N)

#for taking count of closed market hours
tweetcount2 <- tweetcount %>%
  group_by(adjusted_time) %>%
  summarise(N = sum(N)) 



## Dummy for Social Media Post
#find dummy
tweetdummy = dplyr::select(social_hourly,timestamp,adjusted_time,dummy)

#for taking count of closed market hours
tweetdummy2 <- tweetdummy %>%
  group_by(adjusted_time) %>%
  summarise(dummy = sum(dummy)) 
#peculiar interpretation for dummy: if dummy>1 it means that there were x
#out-hours which had tweets in them



## Number of Tweets Mentioning Tariffs 
#find count
tariff = dplyr::select(social_hourly,timestamp,adjusted_time,total_tariff)

#for taking count of closed market hours
tariff2 <- tariff %>%
  group_by(adjusted_time) %>%
  summarise(total_tariff = sum(total_tariff)) 



## Number of Tweets Mentioning Trade 
#find count
trade = dplyr::select(social_hourly,timestamp,adjusted_time,total_trade)

#for taking count of closed market hours
trade2 <- trade %>%
  group_by(adjusted_time) %>%
  summarise(total_trade = sum(total_trade)) 




## Number of Tweets Mentioning China 
#find count
china = dplyr::select(social_hourly,timestamp,adjusted_time,total_china)

#for taking count of closed market hours
china2 <- china %>%
  group_by(adjusted_time) %>%
  summarise(total_china = sum(total_china)) 



## Proportion of Positive 
#find count
positive = dplyr::select(social_hourly,timestamp,adjusted_time,prop_positive)

#how to count outside hours? since proportion?



## Proportion of Negative 
#find count
negative = dplyr::select(social_hourly,timestamp,adjusted_time,prop_negative)



## Merge
#merge our dependant and independant vars

#case 1: ignore tweets outside trading hours
#Vdata = left_join(SPY_volatility, VGK_volatility, by="timestamp")
#Vdata = left_join(Vdata, ASHR_volatility, by="timestamp")
#Vdata = left_join(Vdata, select(tweetdummy, -adjusted_time), by="timestamp")
#Vdata = left_join(Vdata, select(tweetcount, -adjusted_time), by="timestamp")
#Vdata = left_join(Vdata, select(tariff, -adjusted_time), by="timestamp")
#Vdata = left_join(Vdata, select(trade, -adjusted_time), by="timestamp")
#Vdata = left_join(Vdata, select(china, -adjusted_time), by="timestamp")
#Vdata = left_join(Vdata, select(positive, -adjusted_time), by="timestamp")
#Vdata = left_join(Vdata, select(negative, -adjusted_time), by="timestamp")
#rm(Vdata)
#case 2: push tweets made outside market hours to the next open hour
Vdata = left_join(SPY_volatility, VGK_volatility, by="timestamp")
Vdata = left_join(Vdata, ASHR_volatility, by="timestamp")
Vdata <- Vdata %>%
  left_join(tweetdummy2, by = c("timestamp" = "adjusted_time")) 
Vdata <- Vdata %>%
  left_join(tweetcount2, by = c("timestamp" = "adjusted_time")) 
Vdata <- Vdata %>%
  left_join(tariff2, by = c("timestamp" = "adjusted_time")) 
Vdata <- Vdata %>%
  left_join(trade2, by = c("timestamp" = "adjusted_time")) 
Vdata <- Vdata %>%
  left_join(china2, by = c("timestamp" = "adjusted_time")) 

#rename volatility columns
names(Vdata)[2] <- "SPY_vol"
names(Vdata)[3] <- "VGK_vol"
names(Vdata)[4] <- "ASHR_vol"

#convert NA to zeroes
Vdata$N[is.na(Vdata$N)] = 0
Vdata$dummy[is.na(Vdata$dummy)] = 0
Vdata$total_tariff[is.na(Vdata$total_tariff)] = 0
Vdata$total_trade[is.na(Vdata$total_trade)] = 0
Vdata$total_china[is.na(Vdata$total_china)] = 0



#or 

rm(Vdata)
#load final dataset
source(here("helperfunctions/full_data.R"))

#select timeframe 
Vdata = filter(data,between(timestamp, as.Date('2014-01-01'), as.Date('2025-05-07')))
```

```{r series volatility}
#Nombre of lag

#series
pro_v = ts(Vdata$SPY_vol)
autoplot(pro_v)

```

#Information Criteria

```{r AIC}
##with dummy
y = cbind(Vdata$dummy, Vdata$SPY_vol)

y_lag = VARselect(y, lag.max = 150)
y_list = list(y_lag)


##AIC
resultats1 <- lapply(y_list, function(x) x$criteria["AIC(n)", ])

resultats1 = as.data.frame(resultats1)

resultats1 = resultats1 %>%
  rename(name = 1) %>%
  mutate(
    n = c(1:length(name))
  )

ggplot (resultats1, aes(x=n, y= name)) +
  geom_line(color = "steelblue") +
  labs(title = "hourly Returns AIC",x="n" , y = "AIC") +
  theme_minimal()


```

```{r HQ}
##HQ
resultats2 <- lapply(y_list, function(x) x$criteria["HQ(n)", ])

resultats2 = as.data.frame(resultats2)

resultats2 = resultats2 %>%
  rename(name = 1) %>%
  mutate(
    n = c(1:length(name))
  )

ggplot (resultats2, aes(x=n, y= name)) +
  geom_line(color = "steelblue") +
  labs(title = "hourly Returns HQ",x="dum" , y = "HQ") +
  theme_minimal()



```

```{r SC}
##SC
resultats3 <- lapply(y_list, function(x) x$criteria["SC(n)", ])

resultats3 = as.data.frame(resultats3)

resultats3 = resultats3 %>%
  rename(name = 1) %>%
  mutate(
    n = c(1:length(name))
  )

ggplot (resultats3, aes(x=n, y= name)) +
  geom_line(color = "steelblue") +
  labs(title = "hourly Returns SC",x="dum" , y = "SC") +
  theme_minimal()




```

```{r FPE}
##FPE
resultats4 <- lapply(y_list, function(x) x$criteria["FPE(n)", ])

resultats4 = as.data.frame(resultats4)

resultats4 = resultats4 %>%
  rename(name = 1) %>%
  mutate(
    n = c(1:length(name))
  )

ggplot (resultats4, aes(x=n, y= name)) +
  geom_line(color = "steelblue") +
  labs(title = "hourly Returns FPE",x="dum" , y = "FPE") +
  theme_minimal()


```

#Bunch of Test

```{r acf}

y = cbind(Vdata$dummy, Vdata$SPY_vol)
colnames(y)[1:2] <- c("dum", "vol")
est.VAR <- VAR(y,p=6)

acf(Vdata$SPY_vol)


```

```{r pacf}
pacf(Vdata$SPY_vol)


```

```{r adf test for volatility}
adf.test(Vdata$SPY_vol, k = 6)


```

```{r adf test for dummy}
adf.test(Vdata$dummy, k = 6)


```

```{r serial correlation}
serial = serial.test(est.VAR, lags.pt = 20, type = "PT.asymptotic")
###H0 test if there is no serial correlation
###we observe serial correlation
serial


```

```{r plot serial corr}
plot(serial, names = "y1")



```

```{r heteroscedasticity}
hete = arch.test(est.VAR, lags.multi = 80, multivariate.only = TRUE)
hete


```

```{r Does residuals have normal dist.}
norm = normality.test(est.VAR, multivariate.only = TRUE)
norm


```

```{r structural breaks}
stru2 = stability(est.VAR, type ="OLS-CUSUM") #OLS-CUSUM or Rec-CUSUM
plot(stru2)


```

#Main Analysis ##Dummy

```{r Estime dummy}
y = cbind(Vdata$dummy, Vdata$SPY_vol)
colnames(y)[1:2] <- c("dum", "vol")
est.VAR <- VAR(y,p=6)
summary(est.VAR)
Omega <- var(residuals(est.VAR))

```

```{r B mat}
#make the B matrix
loss <- function(param){
  #Define the restriction
  B <- matrix(c(param[1], param[2], 0, param[3]), ncol = 2)
  
  #Make BB' approximatively equal to omega
  X <- Omega - B %*% t(B)
  
  #loss function
  loss <- sum(X^2)
  return(loss)
}

res.opt <- optim(c(1, 0, 1), loss, method = "BFGS")
B.hat <- matrix(c(res.opt$par[1], res.opt$par[2], 0, res.opt$par[3]), ncol = 2)

print(cbind(Omega,B.hat %*% t(B.hat)))


```

```{r error of dum impact}
B.hat


```

```{r IRF dummy}
#get back the coefficient of est.VAR
phi <- Acoef(est.VAR)
PHI = make.PHI(phi)

#take the constant
constant <- sapply(est.VAR$varresult, function(eq) coef(eq)["const"])
c=as.matrix(constant)

#Simulate the IRF
p <- length(phi)
n <- dim(phi[[1]])[1]
nb.sim <- 7*7
par(mfrow=c(2,2))

Y <- simul.VAR(c=c, Phi = phi, B = B.hat, nb.sim ,y0.star=rep(0, n*p),
                indic.IRF = 1, u.shock = c(1,0))
par(mfrow=c(1,1))  
par(plt=c(0.1, 0.9, 0.1, 0.9))
plot(Y[,2],type="l",lwd=2,xlab="",ylab="",main="Effect of XXX on XXX")


```

```{r does vol granger cause dum}
#we want the smaller p-value => h0 test if there is no causality
grangertest(y[,c("vol","dum")], order = 6)




```

```{r does dum granger cause vol}

grangertest(y[,c("dum", "vol")], order = 6)


```

##N

```{r estimate with N}
y2 = cbind(Vdata$N, Vdata$SPY_vol)
colnames(y2)[1:2] <- c("N", "vol")
est.VAR2 <- VAR(y2,p=6)
summary(est.VAR2)
Omega2 <- var(residuals(est.VAR2))


```

```{r B mat2}
#make the B matrix
loss2 <- function(param2){
  #Define the restriction
  B2 <- matrix(c(param2[1], param2[2], 0, param2[3]), ncol = 2)
  
  #Make BB' approximatively equal to omega
  X2 <- Omega2 - B2 %*% t(B2)
  
  #loss function
  loss2 <- sum(X2^2)
  return(loss2)
}

res.opt2 <- optim(c(1, 0, 1), loss2, method = "BFGS")
B.hat2 <- matrix(c(res.opt2$par[1], res.opt2$par[2], 0, res.opt2$par[3]), ncol = 2)

print(cbind(Omega2,B.hat2 %*% t(B.hat2)))


```

```{r shock by N}
B.hat2


```

```{r IRF N}
#get back the coefficient of est.VAR
phi2 <- Acoef(est.VAR2)
PHI2 = make.PHI(phi2)

#take the constant
constant2 <- sapply(est.VAR2$varresult, function(eq) coef(eq)["const"])
c2=as.matrix(constant2)

#Simulate the IRF
p2 <- length(phi2)
n2 <- dim(phi2[[1]])[1]

par(mfrow=c(2,2))
Y2 <- simul.VAR(c=c2, Phi = phi2, B = B.hat2, nb.sim ,y0.star=rep(0, n2*p2),
               indic.IRF = 1, u.shock = c(1,0))
par(mfrow=c(1,1))  
par(plt=c(0.1, 0.9, 0.1, 0.9))
plot(Y2[,2],type="l",lwd=2,xlab="",ylab="",main="Effect of XXX on XXX")




```

```{r does N granger cause vol}
grangertest(y2[,c("N", "vol")], order = 6)



```

```{r does vol granger cause N}
grangertest(y2[,c("vol", "N")], order = 6)



```

##Tariff

```{r estime tariff}
y3 =cbind(Vdata$total_tariff, Vdata$SPY_vol)
colnames(y3)[1:2] <- c("tariff", "vol")
est.VAR3 <- VAR(y3,p=6)
summary(est.VAR3)
Omega3 <- var(residuals(est.VAR3))


```

```{r B mat3}
#make the B matrix
loss3 <- function(param3){
  #Define the restriction
  B3 <- matrix(c(param3[1], param3[2], 0, param3[3]), ncol = 2)
  
  #Make BB' approximatively equal to omega
  X3 <- Omega3 - B3 %*% t(B3)
  
  #loss function
  loss3 <- sum(X3^2)
  return(loss3)
}

res.opt3 <- optim(c(1, 0, 1), loss3, method = "BFGS")
B.hat3 <- matrix(c(res.opt3$par[1], res.opt3$par[2], 0, res.opt3$par[3]), ncol = 2)

print(cbind(Omega3,B.hat3 %*% t(B.hat3)))


```

```{r shock by tarrif}
B.hat3


```

```{r IRF tarrif}
#get back the coefficient of est.VAR
phi3 <- Acoef(est.VAR3)
PHI3 = make.PHI(phi3)

#take the constant
constant3 <- sapply(est.VAR3$varresult, function(eq) coef(eq)["const"])
c3=as.matrix(constant3)

#Simulate the IRF
p3 <- length(phi3)
n3 <- dim(phi3[[1]])[1]

par(mfrow=c(2,2))
Y3 <- simul.VAR(c=c3, Phi = phi3, B = B.hat3, nb.sim ,y0.star=rep(0, n3*p3),
                indic.IRF = 1, u.shock = c(1,0))
par(mfrow=c(1,1))  
par(plt=c(0.1, 0.9, 0.1, 0.9))
plot(Y3[,2],type="l",lwd=2,xlab="",ylab="",main="Effect of XXX on XXX")


```

```{r does vol granger cause tarrif}
grangertest(y3[,c("vol","tariff")], order = 6)



```

```{r does tarrif granger cause vol}
grangertest(y3[,c("tariff", "vol")], order = 6)



```

##Trade

```{r estimate trade}
y4 = cbind(Vdata$total_trade, Vdata$SPY_vol)
colnames(y4)[1:2] <- c("trade", "vol")
est.VAR4 <- VAR(y4,p=6)
summary(est.VAR4)
Omega4 <- var(residuals(est.VAR4))


```

```{r B mat4}
#make the B matrix
loss4 <- function(param4){
  #Define the restriction
  B4 <- matrix(c(param4[1], param4[2], 0, param4[3]), ncol = 2)
  
  #Make BB' approximatively equal to omega
  X4 <- Omega4 - B4 %*% t(B4)
  
  #loss function
  loss4 <- sum(X4^2)
  return(loss4)
}

res.opt4 <- optim(c(1, 0, 1), loss4, method = "BFGS")
B.hat4 <- matrix(c(res.opt4$par[1], res.opt4$par[2], 0, res.opt4$par[3]), ncol = 2)

print(cbind(Omega4,B.hat4 %*% t(B.hat4)))



```

```{r shock by trade}
B.hat3


```

```{r IRF trade}
#get back the coefficient of est.VAR
phi4 <- Acoef(est.VAR4)
PHI4 = make.PHI(phi4)

#take the constant
constant4 <- sapply(est.VAR4$varresult, function(eq) coef(eq)["const"])
c4=as.matrix(constant4)

#Simulate the IRF
p4 <- length(phi4)
n4 <- dim(phi4[[1]])[1]

par(mfrow=c(2,2))
Y4 <- simul.VAR(c=c4, Phi = phi4, B = B.hat4, nb.sim ,y0.star=rep(0, n4*p4),
                indic.IRF = 1, u.shock = c(1,0))
par(mfrow=c(1,1))  
par(plt=c(0.1, 0.9, 0.1, 0.9))
plot(Y4[,2],type="l",lwd=2,xlab="",ylab="",main="Effect of XXX on XXX")



```

```{r does vol granger cause trade}

grangertest(y4[,c("vol","trade")], order = 6)



```

```{r does trade granger cause vol}

grangertest(y4[,c("trade", "vol")], order = 6)


```

##China

```{r estime China}

ychina = cbind(Vdata$total_china, Vdata$SPY_vol)
colnames(ychina)[1:2] <- c("china", "vol")
est.VARchina <- VAR(ychina,p=6)
summary(est.VARchina)
Omegachina <- var(residuals(est.VARchina))


```

```{r B mat china}
#make the B matrix
losschina <- function(paramchina){
  #Define the restriction
  Bchina <- matrix(c(paramchina[1], paramchina[2], 0, paramchina[3]), ncol = 2)
  
  #Make BB' approximatively equal to omega
  Xchina <- Omegachina - Bchina %*% t(Bchina)
  
  #loss function
  losschina <- sum(Xchina^2)
  return(losschina)
}

res.optchina <- optim(c(1, 0, 1), losschina, method = "BFGS")
B.hatchina <- matrix(c(res.optchina$par[1], res.optchina$par[2], 0, res.optchina$par[3]), ncol = 2)

print(cbind(Omegachina,B.hatchina %*% t(B.hatchina)))



```

```{r shock by china}
B.hatchina


```

```{r IRF china}
#get back the coefficient of est.VAR
phichina <- Acoef(est.VARchina)
PHIchina = make.PHI(phichina)

#take the constant
constantchina <- sapply(est.VARchina$varresult, function(eq) coef(eq)["const"])
cchina=as.matrix(constantchina)

#Simulate the IRF
pchina <- length(phichina)
nchina <- dim(phichina[[1]])[1]

par(mfrow=c(2,2))
Ychina <- simul.VAR(c=cchina, Phi = phichina, B = B.hatchina, nb.sim ,y0.star=rep(0, nchina*pchina),
                    indic.IRF = 1, u.shock = c(1,0))
par(mfrow=c(1,1))  
par(plt=c(0.1, 0.9, 0.1, 0.9))
plot(Ychina[,2],type="l",lwd=2,xlab="",ylab="",main="Effect of XXX on XXX")



```

```{r does vol granger cause china}

grangertest(ychina[,c("vol", "china")], order = 6)



```

```{r does china granger cause vol}

grangertest(ychina[,c("china", "vol")], order = 6)


```

#Sentiment Analysis

```{r sentiment analysis data load}

##sentiment analysis(N)

Vdata2 = left_join(SPY_volatility, VGK_volatility, by="timestamp")
Vdata2 = left_join(Vdata2, ASHR_volatility, by="timestamp")


#positive
positive = dplyr::select(social_hourly, timestamp, adjusted_time, positive)
positive2 <- positive %>%
  group_by(adjusted_time) %>%
  summarise(positive = sum(positive))

Vdata2 <- Vdata2 %>%
  left_join(positive2, by = c("timestamp" = "adjusted_time"))
Vdata2$positive[is.na(Vdata2$positive)] = 0

#negative
negative = dplyr::select(social_hourly, timestamp, adjusted_time, negative)
negative2 <- negative %>%
  group_by(adjusted_time) %>%
  summarise(negative = sum(negative))
Vdata2 <- Vdata2 %>%
  left_join(negative2, by = c("timestamp" = "adjusted_time"))
Vdata2$negative[is.na(Vdata2$negative)] = 0

#trust
trust = dplyr::select(social_hourly, timestamp, adjusted_time, trust)
trust2 <- trust %>%
  group_by(adjusted_time) %>%
  summarise(trust = sum(trust))
Vdata2 <- Vdata2 %>%
  left_join(trust2, by = c("timestamp" = "adjusted_time"))
Vdata2$trust[is.na(Vdata2$trust)] = 0

#surprise
surprise = dplyr::select(social_hourly, timestamp, adjusted_time, surprise)
surprise2 <- surprise %>%
  group_by(adjusted_time) %>%
  summarise(surprise = sum(surprise))
Vdata2 <- Vdata2 %>%
  left_join(surprise2, by = c("timestamp" = "adjusted_time"))
Vdata2$surprise[is.na(Vdata2$surprise)] = 0

#sadness
sadness = dplyr::select(social_hourly, timestamp, adjusted_time, sadness)
sadness2 <- sadness %>%
  group_by(adjusted_time) %>%
  summarise(sadness = sum(sadness))
Vdata2 <- Vdata2 %>%
  left_join(sadness2, by = c("timestamp" = "adjusted_time"))
Vdata2$sadness[is.na(Vdata2$sadness)] = 0

#joy
joy = dplyr::select(social_hourly, timestamp, adjusted_time, joy)
joy2 <- joy %>%
  group_by(adjusted_time) %>%
  summarise(joy = sum(joy))
Vdata2 <- Vdata2 %>%
  left_join(joy2, by = c("timestamp" = "adjusted_time"))
Vdata2$joy[is.na(Vdata2$joy)] = 0

#fear
fear = dplyr::select(social_hourly, timestamp, adjusted_time, fear)
fear2 <- fear %>%
  group_by(adjusted_time) %>%
  summarise(fear = sum(fear))
Vdata2 <- Vdata2 %>%
  left_join(fear2, by = c("timestamp" = "adjusted_time"))
Vdata2$fear[is.na(Vdata2$fear)] = 0

#disgust
disgust = dplyr::select(social_hourly, timestamp, adjusted_time, disgust)
disgust2 <- disgust %>%
  group_by(adjusted_time) %>%
  summarise(disgust = sum(disgust))
Vdata2 <- Vdata2 %>%
  left_join(disgust2, by = c("timestamp" = "adjusted_time"))
Vdata2$disgust[is.na(Vdata2$disgust)] = 0

#anticipation
anticipation = dplyr::select(social_hourly, timestamp, adjusted_time, anticipation)
anticipation2 <- anticipation %>%
  group_by(adjusted_time) %>%
  summarise(anticipation = sum(anticipation))
Vdata2 <- Vdata2 %>%
  left_join(anticipation2, by = c("timestamp" = "adjusted_time"))
Vdata2$anticipation[is.na(Vdata2$anticipation)] = 0

#anger
anger = dplyr::select(social_hourly, timestamp, adjusted_time, anger)
anger2 <- anger %>%
  group_by(adjusted_time) %>%
  summarise(anger = sum(anger))
Vdata2 <- Vdata2 %>%
  left_join(anger2, by = c("timestamp" = "adjusted_time"))
Vdata2$anger[is.na(Vdata2$anger)] = 0


#rename volatility columns
names(Vdata2)[2] <- "SPY_vol"
names(Vdata2)[3] <- "VGK_vol"
names(Vdata2)[4] <- "ASHR_vol"





```

```{r estime positive }
y5 = cbind(Vdata2$positive, Vdata2$SPY_vol)
colnames(y5)[1:2] <- c("positive", "vol")
est.VAR5 <- VAR(y5,p=6)
summary(est.VAR5)
Omega5 <- var(residuals(est.VAR5))


```

```{r B mat5}
#make the B matrix
loss5 <- function(param5){
  #Define the restriction
  B5 <- matrix(c(param5[1], param5[2], 0, param5[3]), ncol = 2)
  
  #Make BB' approximatively equal to omega
  X5 <- Omega5 - B5 %*% t(B5)
  
  #loss function
  loss5 <- sum(X5^2)
  return(loss5)
}

res.opt5 <- optim(c(1, 0, 1), loss5, method = "BFGS")
B.hat5 <- matrix(c(res.opt5$par[1], res.opt5$par[2], 0, res.opt5$par[3]), ncol = 2)

print(cbind(Omega5,B.hat5 %*% t(B.hat5)))



```

```{r shock by positive}
B.hat5


```

```{r IRF positive}
#get back the coefficient of est.VAR
phi5 <- Acoef(est.VAR5)
PHI5 = make.PHI(phi5)

#take the constant
constant5 <- sapply(est.VAR5$varresult, function(eq) coef(eq)["const"])
c5=as.matrix(constant5)

#Simulate the IRF
p5 <- length(phi5)
n5 <- dim(phi5[[1]])[1]

par(mfrow=c(2,2))
Y5 <- simul.VAR(c=c5, Phi = phi5, B = B.hat5, nb.sim ,y0.star=rep(0, n5*p5),
                  indic.IRF = 1, u.shock = c(1,0))
par(mfrow=c(1,1))  
par(plt=c(0.1, 0.9, 0.1, 0.9))
plot(Y5[,2],type="l",lwd=2,xlab="",ylab="",main="Effect of XXX on XXX")




```

```{r does vol granger cause positive}
grangertest(y5[,c("vol","positive")], order = 6)



```

```{r does positive granger cause vol}
grangertest(y5[,c("positive", "vol")], order = 6)


```

```{r estimate negative}
y6 = cbind(Vdata2$negative, Vdata2$SPY_vol)
colnames(y6)[1:2] <- c("negative", "vol")
est.VAR6 <- VAR(y6,p=6)
summary(est.VAR6)
Omega6 <- var(residuals(est.VAR6))


```

```{r B mat6}
#make the B matrix
loss6 <- function(param6){
  #Define the restriction
  B6 <- matrix(c(param6[1], param6[2], 0, param6[3]), ncol = 2)
  
  #Make BB' approximatively equal to omega
  X6 <- Omega6 - B6 %*% t(B6)
  
  #loss function
  loss6 <- sum(X6^2)
  return(loss6)
}

res.opt6 <- optim(c(1, 0, 1), loss6, method = "BFGS")
B.hat6 <- matrix(c(res.opt6$par[1], res.opt6$par[2], 0, res.opt6$par[3]), ncol = 2)

print(cbind(Omega6,B.hat6 %*% t(B.hat6)))


```

```{r shock by negative}
B.hat6


```

```{r IRF negative}
#get back the coefficient of est.VAR
phi6 <- Acoef(est.VAR6)
PHI6 = make.PHI(phi6)

#take the constant
constant6 <- sapply(est.VAR6$varresult, function(eq) coef(eq)["const"])
c6=as.matrix(constant6)

#Simulate the IRF
p6 <- length(phi6)
n6 <- dim(phi6[[1]])[1]

par(mfrow=c(2,2))
Y6 <- simul.VAR(c=c6, Phi = phi6, B = B.hat6, nb.sim ,y0.star=rep(0, n6*p6),
                  indic.IRF = 1, u.shock = c(1,0))
par(mfrow=c(1,1))  
par(plt=c(0.1, 0.9, 0.1, 0.9))
plot(Y6[,2],type="l",lwd=2,xlab="",ylab="",main="Effect of XXX on XXX")



```

```{r estimate truste}
y7 = cbind(Vdata2$trust, Vdata2$SPY_vol)
colnames(y7)[1:2] <- c("trust", "vol")
est.VAR7 <- VAR(y7,p=6)
summary(est.VAR7)
Omega7 <- var(residuals(est.VAR7))


```

```{r B mat7}
#make the B matrix
loss7 <- function(param7){
  #Define the restriction
  B7 <- matrix(c(param7[1], param7[2], 0, param7[3]), ncol = 2)
  
  #Make BB' approximatively equal to omega
  X7 <- Omega7 - B7 %*% t(B7)
  
  #loss function
  loss7 <- sum(X7^2)
  return(loss7)
}

res.opt7 <- optim(c(1, 0, 1), loss7, method = "BFGS")
B.hat7 <- matrix(c(res.opt7$par[1], res.opt7$par[2], 0, res.opt7$par[3]), ncol = 2)

print(cbind(Omega7,B.hat7 %*% t(B.hat7)))



```

```{r shock by trust}
B.hat7


```

```{r IRF trust}

#get back the coefficient of est.VAR
phi7 <- Acoef(est.VAR7)
PHI7 = make.PHI(phi7)

#take the constant
constant7 <- sapply(est.VAR7$varresult, function(eq) coef(eq)["const"])
c7=as.matrix(constant7)

#Simulate the IRF
p7 <- length(phi7)
n7 <- dim(phi7[[1]])[1]

par(mfrow=c(2,2))
Y7 <- simul.VAR(c=c7, Phi = phi7, B = B.hat7, nb.sim ,y0.star=rep(0, n7*p7),
                  indic.IRF = 1, u.shock = c(1,0))
par(mfrow=c(1,1))  
par(plt=c(0.1, 0.9, 0.1, 0.9))
plot(Y7[,2],type="l",lwd=2,xlab="",ylab="",main="Effect of XXX on XXX")



```

```{r estimate surprise}

y8 = cbind(Vdata2$surprise, Vdata2$SPY_vol)
colnames(y8)[1:2] <- c("surprise", "vol")
est.VAR8 <- VAR(y8,p=6)
summary(est.VAR8)
Omega8 <- var(residuals(est.VAR8))


```

```{r Bmat8}

#make the B matrix
loss8 <- function(param8){
  #Define the restriction
  B8 <- matrix(c(param8[1], param8[2], 0, param8[3]), ncol = 2)
  
  #Make BB' approximatively equal to omega
  X8 <- Omega8 - B8 %*% t(B8)
  
  #loss function
  loss8 <- sum(X8^2)
  return(loss8)
}

res.opt8 <- optim(c(1, 0, 1), loss8, method = "BFGS")
B.hat8 <- matrix(c(res.opt8$par[1], res.opt8$par[2], 0, res.opt8$par[3]), ncol = 2)

print(cbind(Omega8,B.hat8 %*% t(B.hat8)))

```

```{r shock by surprise}
#get back the coefficient of est.VAR
phi8 <- Acoef(est.VAR8)
PHI8 = make.PHI(phi8)

#take the constant
constant8 <- sapply(est.VAR8$varresult, function(eq) coef(eq)["const"])
c8=as.matrix(constant8)

#Simulate the IRF
p8 <- length(phi8)
n8 <- dim(phi8[[1]])[1]

par(mfrow=c(2,2))
Y8 <- simul.VAR(c=c8, Phi = phi8, B = B.hat8, nb.sim ,y0.star=rep(0, n8*p8),
                  indic.IRF = 1, u.shock = c(1,0))
par(mfrow=c(1,1))  
par(plt=c(0.1, 0.9, 0.1, 0.9))
plot(Y8[,2],type="l",lwd=2,xlab="",ylab="",main="Effect of XXX on XXX")


```

```{r estimate sadness}
y9 = cbind(Vdata2$sadness, Vdata2$SPY_vol)
colnames(y9)[1:2] <- c("sadness", "vol")
est.VAR9 <- VAR(y9,p=6)
summary(est.VAR9)
Omega9 <- var(residuals(est.VAR9))


```

```{r b mat lutin}
#make the B matrix
loss9 <- function(param9){
  #Define the restriction
  B9 <- matrix(c(param9[1], param9[2], 0, param9[3]), ncol = 2)
  
  #Make BB' approximatively equal to omega
  X9 <- Omega9 - B9 %*% t(B9)
  
  #loss function
  loss9 <- sum(X9^2)
  return(loss9)
}

res.opt9 <- optim(c(1, 0, 1), loss9, method = "BFGS")
B.hat9 <- matrix(c(res.opt9$par[1], res.opt9$par[2], 0, res.opt9$par[3]), ncol = 2)

print(cbind(Omega9,B.hat9 %*% t(B.hat9)))


```

```{r shock by sadnes ;(}

B.hat9

```

```{r IRF sadness}
#get back the coefficient of est.VAR
phi9 <- Acoef(est.VAR9)
PHI9 = make.PHI(phi9)

#take the constant
constant9 <- sapply(est.VAR9$varresult, function(eq) coef(eq)["const"])
c9=as.matrix(constant9)

#Simulate the IRF
p9 <- length(phi9)
n9 <- dim(phi9[[1]])[1]

par(mfrow=c(2,2))
Y9 <- simul.VAR(c=c9, Phi = phi9, B = B.hat9, nb.sim ,y0.star=rep(0, n9*p9),
                  indic.IRF = 1, u.shock = c(1,0))
par(mfrow=c(1,1))  
par(plt=c(0.1, 0.9, 0.1, 0.9))
plot(Y9[,2],type="l",lwd=2,xlab="",ylab="",main="Effect of XXX on XXX")



```

```{r estimate joy}

y10 = cbind(Vdata2$joy, Vdata2$SPY_vol)
colnames(y10)[1:2] <- c("joy", "vol")
est.VAR10 <- VAR(y10,p=6)
summary(est.VAR10)
Omega10 <- var(residuals(est.VAR10))


```

```{r Bmat joy}
#make the B matrix
loss10 <- function(param10){
  #Define the restriction
  B10 <- matrix(c(param10[1], param10[2], 0, param10[3]), ncol = 2)
  
  #Make BB' approximatively equal to omega
  X10 <- Omega10 - B10 %*% t(B10)
  
  #loss function
  loss10 <- sum(X10^2)
  return(loss10)
}

res.opt10 <- optim(c(1, 0, 1), loss10, method = "BFGS")
B.hat10 <- matrix(c(res.opt10$par[1], res.opt10$par[2], 0, res.opt10$par[3]), ncol = 2)

print(cbind(Omega10,B.hat10 %*% t(B.hat10)))


```

```{r shock by joy}

B.hat10

```

```{r IRF joy}
#get back the coefficient of est.VAR
phi10 <- Acoef(est.VAR10)
PHI10 = make.PHI(phi10)

#take the constant
constant10 <- sapply(est.VAR10$varresult, function(eq) coef(eq)["const"])
c10=as.matrix(constant10)

#Simulate the IRF
p10 <- length(phi10)
n10 <- dim(phi10[[1]])[1]

par(mfrow=c(2,2))
Y10 <- simul.VAR(c=c10, Phi = phi10, B = B.hat10, nb.sim ,y0.star=rep(0, n10*p10),
                  indic.IRF = 1, u.shock = c(1,0))
par(mfrow=c(1,1))  
par(plt=c(0.1, 0.9, 0.1, 0.9))
plot(Y10[,2],type="l",lwd=2,xlab="",ylab="",main="Effect of XXX on XXX")




```

```{r estimate fear}
y10 = cbind(Vdata2$fear, Vdata2$SPY_vol)
colnames(y10)[1:2] <- c("fear", "vol")
est.VAR10 <- VAR(y10,p=6)
summary(est.VAR10)
Omega10 <- var(residuals(est.VAR10))


```

```{r bmat fear}
#make the B matrix
loss10 <- function(param10){
  #Define the restriction
  B10 <- matrix(c(param10[1], param10[2], 0, param10[3]), ncol = 2)
  
  #Make BB' approximatively equal to omega
  X10 <- Omega10 - B10 %*% t(B10)
  
  #loss function
  loss10 <- sum(X10^2)
  return(loss10)
}

res.opt10 <- optim(c(1, 0, 1), loss10, method = "BFGS")
B.hat10 <- matrix(c(res.opt10$par[1], res.opt10$par[2], 0, res.opt10$par[3]), ncol = 2)

print(cbind(Omega10,B.hat10 %*% t(B.hat10)))


```

```{r shock by fear}
B.hat10


```

```{r IRF fear}
#get back the coefficient of est.VAR
phi10 <- Acoef(est.VAR10)
PHI10 = make.PHI(phi10)

#take the constant
constant10 <- sapply(est.VAR10$varresult, function(eq) coef(eq)["const"])
c10=as.matrix(constant10)

#Simulate the IRF
p10 <- length(phi10)
n10 <- dim(phi10[[1]])[1]

par(mfrow=c(2,2))
Y10 <- simul.VAR(c=c10, Phi = phi10, B = B.hat10, nb.sim ,y0.star=rep(0, n10*p10),
                  indic.IRF = 1, u.shock = c(1,0))
par(mfrow=c(1,1))  
par(plt=c(0.1, 0.9, 0.1, 0.9))
plot(Y10[,2],type="l",lwd=2,xlab="",ylab="",main="Effect of XXX on XXX")



```

```{r estimate disgust}
y11 = cbind(Vdata2$disgust, Vdata2$SPY_vol)
colnames(y11)[1:2] <- c("disgust", "vol")
est.VAR11 <- VAR(y11,p=6)
summary(est.VAR11)
Omega11 <- var(residuals(est.VAR11))



```

```{r bmat disgust}
#make the B matrix
loss11 <- function(param11){
  #Define the restriction
  B11 <- matrix(c(param11[1], param11[2], 0, param11[3]), ncol = 2)
  
  #Make BB' approximatively equal to omega
  X11 <- Omega11 - B11 %*% t(B11)
  
  #loss function
  loss11 <- sum(X11^2)
  return(loss11)
}

res.opt11 <- optim(c(1, 0, 1), loss11, method = "BFGS")
B.hat11 <- matrix(c(res.opt11$par[1], res.opt11$par[2], 0, res.opt11$par[3]), ncol = 2)

print(cbind(Omega11,B.hat11 %*% t(B.hat11)))


```

```{r shock by disgust}
B.hat11


```

```{r IRF disgust}
#get back the coefficient of est.VAR
phi11 <- Acoef(est.VAR11)
PHI11 = make.PHI(phi11)

#take the constant
constant11 <- sapply(est.VAR11$varresult, function(eq) coef(eq)["const"])
c11=as.matrix(constant11)

#Simulate the IRF
p11 <- length(phi11)
n11 <- dim(phi11[[1]])[1]

par(mfrow=c(2,2))
Y11 <- simul.VAR(c=c11, Phi = phi11, B = B.hat11, nb.sim ,y0.star=rep(0, n11*p11),
                  indic.IRF = 1, u.shock = c(1,0))
par(mfrow=c(1,1))  
par(plt=c(0.1, 0.9, 0.1, 0.9))
plot(Y11[,2],type="l",lwd=2,xlab="",ylab="",main="Effect of XXX on XXX")


```

```{r estimate anticipation}
y15 = cbind(Vdata2$anticipation, Vdata2$SPY_vol)
colnames(y15)[1:2] <- c("anticipation", "vol")
est.VAR15 <- VAR(y15,p=6)
summary(est.VAR15)
Omega15 <- var(residuals(est.VAR15))



```

```{r bmat15}
#make the B matrix
loss15 <- function(param15){
  #Define the restriction
  B15 <- matrix(c(param15[1], param15[2], 0, param15[3]), ncol = 2)
  
  #Make BB' approximatively equal to omega
  X15 <- Omega15 - B15 %*% t(B15)
  
  #loss function
  loss15 <- sum(X15^2)
  return(loss15)
}

res.opt15 <- optim(c(1, 0, 1), loss15, method = "BFGS")
B.hat15 <- matrix(c(res.opt15$par[1], res.opt15$par[2], 0, res.opt15$par[3]), ncol = 2)

print(cbind(Omega15,B.hat15 %*% t(B.hat15)))



```

```{r shock by anticipation}
#get back the coefficient of est.VAR
phi15 <- Acoef(est.VAR15)
PHI15 = make.PHI(phi15)

#take the constant
constant15 <- sapply(est.VAR15$varresult, function(eq) coef(eq)["const"])
c15=as.matrix(constant15)

#Simulate the IRF
p15 <- length(phi15)
n15 <- dim(phi15[[1]])[1]

par(mfrow=c(2,2))
y15 <- simul.VAR(c=c15, Phi = phi15, B = B.hat15, nb.sim ,y0.star=rep(0, n15*p15),
                  indic.IRF = 1, u.shock = c(1,0))
par(mfrow=c(1,1))  
par(plt=c(0.1, 0.9, 0.1, 0.9))
plot(y15[,2],type="l",lwd=2,xlab="",ylab="",main="Effect of XXX on XXX")




```

```{r estimate anger}
y16 = cbind(Vdata2$anger, Vdata2$SPY_vol)
colnames(y16)[1:2] <- c("anger", "vol")
est.VAR16 <- VAR(y16,p=6)
summary(est.VAR16)
Omega16 <- var(residuals(est.VAR16))


```

```{r bmat16}

#make the B matrix
loss16 <- function(param16){
  #Define the restriction
  B16 <- matrix(c(param16[1], param16[2], 0, param16[3]), ncol = 2)
  
  #Make BB' approximatively equal to omega
  X16 <- Omega16 - B16 %*% t(B16)
  
  #loss function
  loss16 <- sum(X16^2)
  return(loss16)
}

res.opt16 <- optim(c(1, 0, 1), loss16, method = "BFGS")
B.hat16 <- matrix(c(res.opt16$par[1], res.opt16$par[2], 0, res.opt16$par[3]), ncol = 2)

print(cbind(Omega16,B.hat16 %*% t(B.hat16)))

```

```{r shock by anger}
B.hat16


```

```{r IRF anger}
#get back the coefficient of est.VAR
phi16 <- Acoef(est.VAR16)
PHI16 = make.PHI(phi16)

#take the constant
constant16 <- sapply(est.VAR16$varresult, function(eq) coef(eq)["const"])
c16=as.matrix(constant16)

#Simulate the IRF
p16 <- length(phi16)
n16 <- dim(phi16[[1]])[1]

par(mfrow=c(2,2))
Y16 <- simul.VAR(c=c16, Phi = phi16, B = B.hat16, nb.sim ,y0.star=rep(0, n16*p16),
                  indic.IRF = 1, u.shock = c(1,0))
par(mfrow=c(1,1))  
par(plt=c(0.1, 0.9, 0.1, 0.9))
plot(Y16[,2],type="l",lwd=2,xlab="",ylab="",main="Effect of XXX on XXX")




```

#interaction

##N and tariff, 2 variables

```{r estimate int N tariff}
int1 = Vdata$total_tariff * Vdata$N
y12 = cbind(int1, Vdata$SPY_vol)
colnames(y12)[1:2] <- c("interaction", "vol")
est.VAR12 <- VAR(y12,p=6)
summary(est.VAR12)
Omega12 <- var(residuals(est.VAR12))


```

```{r bhat12}
#make the B matrix
loss12 <- function(param12){
  #Define the restriction
  B12 <- matrix(c(param12[1], param12[2], 0, param12[3]), ncol = 2)
  
  #Make BB' approximatively equal to omega
  X12 <- Omega12 - B12 %*% t(B12)
  
  #loss function
  loss12 <- sum(X12^2)
  return(loss12)
}

res.opt12 <- optim(c(1, 0, 1), loss12, method = "BFGS")
B.hat12 <- matrix(c(res.opt12$par[1], res.opt12$par[2], 0, res.opt12$par[3]), ncol = 2)

print(cbind(Omega12,B.hat12 %*% t(B.hat12)))


```

```{r shock by int of N and tariff}
B.hat12


```

```{r IRF int1}
#get back the coefficient of est.VAR
phi12 <- Acoef(est.VAR12)
PHI12 = make.PHI(phi12)

#take the constant
constant12 <- sapply(est.VAR12$varresult, function(eq) coef(eq)["const"])
c12=as.matrix(constant12)

#Simulate the IRF
p12 <- length(phi12)
n12 <- dim(phi12[[1]])[1]

par(mfrow=c(2,2))
Y12 <- simul.VAR(c=c12, Phi = phi12, B = B.hat12, nb.sim ,y0.star=rep(0, n12*p12),
                  indic.IRF = 1, u.shock = c(1,0))
par(mfrow=c(1,1))  
par(plt=c(0.1, 0.9, 0.1, 0.9))
plot(Y12[,2],type="l",lwd=2,xlab="",ylab="",main="Effect of XXX on XXX")




```

##N and tariff, 3 variables

```{r estimate int Ntariff with N}

y12.2 = cbind(Vdata$total_trade, int1)
y12.2 = cbind(y12.2, Vdata$SPY_vol)
colnames(y12.2)[1:3] <- c("tariff", "Ntariff", "vol")
est.VAR12.2 <- VAR(y12.2,p=6)
summary(est.VAR12.2)
Omega12.2 <- var(residuals(est.VAR12.2))


```

```{r bmat12.2}
#make the B matrix
loss12.2 <- function(param12.2){
  #Define the restriction
  B12.2 <- matrix(c(param12.2[1], param12.2[2], param12.2[3], 0, param12.2[4],param12.2[5], 0, 0,param12.2[6]), ncol = 3)
  
  #Make BB' approximatively equal to omega
  X12.2 <- Omega12.2 - B12.2 %*% t(B12.2)
  
  #loss function
  loss12.2 <- sum(X12.2^2)
  return(loss12.2)
}

res.opt12.2 <- optim(c(1, 0, 0, 1, 0, 1), loss12.2, method = "BFGS")
B.hat12.2 <- matrix(c(res.opt12.2$par[1], res.opt12.2$par[2], res.opt12.2$par[3], 0, res.opt12.2$par[4], res.opt12.2$par[5], 0, 0, res.opt12.2$par[6]), ncol = 3)

print(cbind(Omega12.2,B.hat12.2 %*% t(B.hat12.2)))


```

```{r shock by N and Ntariff}
B.hat12.2


```

```{r IRFs int1 and tariff}

#get back the coefficient of est.VAR
phi12.2 <- Acoef(est.VAR12.2)
PHI12.2 = make.PHI(phi12.2)

#take the constant
constant12.2 <- sapply(est.VAR12.2$varresult, function(eq) coef(eq)["const"])
c12.2=as.matrix(constant12.2)

#Simulate the IRF
p12.2 <- length(phi12.2)
n12.2 <- dim(phi12.2[[1]])[1]

par(mfrow=c(2,2))
y12.2.N <- simul.VAR(c=c12.2, Phi = phi12.2, B = B.hat12.2, nb.sim ,y0.star=rep(0, n12.2*p12.2),
                 indic.IRF = 1, u.shock = c(1,0,0))
y12.2.I <- simul.VAR(c=c12.2, Phi = phi12.2, B = B.hat12.2, nb.sim ,y0.star=rep(0, n12.2*p12.2),
                     indic.IRF = 1, u.shock = c(0,1,0))
par(mfrow=c(1,2))  
plot(y12.2.N[,3],type="l",lwd=2,xlab="",ylab="",main="N on Volatility")
plot(y12.2.I[,3],type="l",lwd=2,xlab="",ylab="",main="int on Volatility")



```

##positive and negative

```{r estime pos/neg}
y13 = cbind(Vdata2$positive, Vdata2$negative)
y13 = cbind(y13, Vdata2$SPY_vol)
colnames(y13)[1:3] <- c("positive", "negative", "vol")
est.VAR13 <- VAR(y13,p=6)
summary(est.VAR13)
Omega13 <- var(residuals(est.VAR13))


```

```{r Bmat13}
#make the B matrix
loss13 <- function(param13){
  #Define the restriction
  B13 <- matrix(c(param13[1], param13[2], param13[3], 0, param13[4],param13[5], 0, 0,param13[6]), ncol = 3)
  
  #Make BB' approximatively equal to omega
  X13 <- Omega13 - B13 %*% t(B13)
  
  #loss function
  loss13 <- sum(X13^2)
  return(loss13)
}

res.opt13 <- optim(c(1, 0, 0, 1, 0, 1), loss13, method = "BFGS")
B.hat13 <- matrix(c(res.opt13$par[1], res.opt13$par[2], res.opt13$par[3], 0, res.opt13$par[4], res.opt13$par[5], 0, 0, res.opt13$par[6]), ncol = 3)

print(cbind(Omega13,B.hat13 %*% t(B.hat13)))



```

```{r shock by pos/neg}

B.hat13

```

```{r IRFS pos/neg}
#get back the coefficient of est.VAR
phi13 <- Acoef(est.VAR13)
PHI13 = make.PHI(phi13)

#take the constant
constant13 <- sapply(est.VAR13$varresult, function(eq) coef(eq)["const"])
c13=as.matrix(constant13)

#Simulate the IRF
p13 <- length(phi13)
n13 <- dim(phi13[[1]])[1]

par(mfrow=c(2,2))
y13.N <- simul.VAR(c=c13, Phi = phi13, B = B.hat13, nb.sim ,y0.star=rep(0, n13*p13),
                     indic.IRF = 1, u.shock = c(1,0,0))
y13.I <- simul.VAR(c=c13, Phi = phi13, B = B.hat13, nb.sim ,y0.star=rep(0, n13*p13),
                     indic.IRF = 1, u.shock = c(0,1,0))
par(mfrow=c(1,2))  
plot(y13.N[,3],type="l",lwd=2,xlab="",ylab="",main="N on Volatility")
plot(y13.I[,3],type="l",lwd=2,xlab="",ylab="",main="int on Volatility")



```

```{r grangertest}

grangertest(y13[,c("positive","vol")], order = 6)
grangertest(y13[,c("negative","vol")], order = 6)
grangertest(y13[,c("vol","positive")], order = 6)
grangertest(y13[,c("vol","negative")], order = 6)

#seems to not have any granger causalities

```

#N and trade, 2 variables

```{r estimate Ntrade}
int5 = Vdata$total_trade * Vdata$N

y14 = cbind(int5, Vdata$SPY_vol)
colnames(y14)[1:2] <- c("Ntrade", "vol")
est.VAR14 <- VAR(y14,p=6)
summary(est.VAR14)
Omega14 <- var(residuals(est.VAR14))



```

```{r bmat14}
#make the B matrix
loss14 <- function(param14){
  #Define the restriction
  B14 <- matrix(c(param14[1], param14[2], 0, param14[3]), ncol = 2)
  
  #Make BB' approximatively equal to omega
  X14 <- Omega14 - B14 %*% t(B14)
  
  #loss function
  loss14 <- sum(X14^2)
  return(loss14)
}

res.opt14 <- optim(c(1, 0, 1), loss14, method = "BFGS")
B.hat14 <- matrix(c(res.opt14$par[1], res.opt14$par[2], 0, res.opt14$par[3]), ncol = 2)

print(cbind(Omega14,B.hat14 %*% t(B.hat14)))



```

```{r IRF Ntrade}
#get back the coefficient of est.VAR
phi14 <- Acoef(est.VAR14)
PHI14 = make.PHI(phi14)

#take the constant
constant14 <- sapply(est.VAR14$varresult, function(eq) coef(eq)["const"])
c14=as.matrix(constant14)

#Simulate the IRF
p14 <- length(phi14)
n14 <- dim(phi14[[1]])[1]

par(mfrow=c(2,2))
Y14 <- simul.VAR(c=c14, Phi = phi14, B = B.hat14, nb.sim ,y0.star=rep(0, n14*p14),
                  indic.IRF = 1, u.shock = c(1,0))
par(mfrow=c(1,1))  
par(plt=c(0.1, 0.9, 0.1, 0.9))
plot(Y14[,2],type="l",lwd=2,xlab="",ylab="",main="Effect of XXX on XXX")



```

##N and tariff, 3 variables

```{r Estimate Ntariff with tariff}

y14.2 = cbind(Vdata$total_trade, int5)
y14.2 = cbind(y14.2, Vdata$SPY_vol)
colnames(y14.2)[1:3] <- c("trade", "Ntrade", "vol")
est.VAR14.2 <- VAR(y14.2,p=6)
summary(est.VAR14.2)
Omega14.2 <- var(residuals(est.VAR14.2))

```

```{r Bmat14.2}
#make the B matrix
loss14.2 <- function(param14.2){
  #Define the restriction
  B14.2 <- matrix(c(param14.2[1], param14.2[2], param14.2[3], 0, param14.2[4],param14.2[5], 0, 0,param14.2[6]), ncol = 3)
  
  #Make BB' approximatively equal to omega
  X14.2 <- Omega14.2 - B14.2 %*% t(B14.2)
  
  #loss function
  loss14.2 <- sum(X14.2^2)
  return(loss14.2)
}

res.opt14.2 <- optim(c(1, 0, 0, 1, 0, 1), loss14.2, method = "BFGS")
B.hat14.2 <- matrix(c(res.opt14.2$par[1], res.opt14.2$par[2], res.opt14.2$par[3], 0, res.opt14.2$par[4], res.opt14.2$par[5], 0, 0, res.opt14.2$par[6]), ncol = 3)

print(cbind(Omega14.2,B.hat14.2 %*% t(B.hat14.2)))



```

```{r shock by Ntariff and tariff}

B.hat14.2

```

```{r IRF Ntariff and tariff}
#get back the coefficient of est.VAR
phi14.2 <- Acoef(est.VAR14.2)
PHI14.2 = make.PHI(phi14.2)

#take the constant
constant14.2 <- sapply(est.VAR14.2$varresult, function(eq) coef(eq)["const"])
c14.2=as.matrix(constant14.2)

#Simulate the IRF
p14.2 <- length(phi14.2)
n14.2 <- dim(phi14.2[[1]])[1]

y14.2.N <- simul.VAR(c=c14.2, Phi = phi14.2, B = B.hat14.2, nb.sim ,y0.star=rep(0, n14.2*p14.2),
                     indic.IRF = 1, u.shock = c(1,0,0))
y14.2.I <- simul.VAR(c=c14.2, Phi = phi14.2, B = B.hat14.2, nb.sim ,y0.star=rep(0, n14.2*p14.2),
                     indic.IRF = 1, u.shock = c(0,1,0))
par(mfrow=c(1,2))  
plot(y14.2.N[,3],type="l",lwd=2,xlab="",ylab="",main="N on Volatility")
plot(y14.2.I[,3],type="l",lwd=2,xlab="",ylab="",main="int on Volatility")




```

```{r }



```

```{r }



```

```{r }



```

```{r }



```

```{r }



```

```{r }



```

```{r }



```

```{r }



```

```{r }



```

```{r }



```

```{r }



```

```{r }



```

```{r }



```

```{r }



```

```{r }



```

```{r }



```

```{r }



```

```{r }



```

```{r }



```

```{r }



```

```{r }



```

```{r }



```

```{r }



```

```{r }



```

```{r }



```

```{r }



```

```{r }



```

```{r }



```

```{r }



```

```{r }



```

```{r }



```

```{r }



```

```{r }



```

```{r }



```

```{r }



```

```{r }



```

```{r }



```

```{r }



```

```{r }



```

```{r }



```

```{r }



```

```{r }



```

```{r }



```

```{r }



```

```{r }



```

```{r }



```

```{r }



```

```{r }



```

```{r }



```

```{r }



```

```{r }



```

```{r }



```

```{r }



```

```{r }



```

```{r }



```
