---
title: "VGK Data Descriptive Analysis"
output:
  pdf_document: 
    toc: true
    fig_caption: yes
    latex_engine: lualatex
header-includes:
  - \usepackage{amsmath}
---
\newpage

```{r library_setup, results=FALSE, warning=FALSE, message=FALSE, echo=FALSE}
rm(list=ls())
require(tinytex) #LaTeX
require(ggplot2) #plots
require(AEC) #JP-Renne functions
require(forecast) #time series stuff
require(expm) #matrix exponents
require(here) #directory finder
require(stringr) # analysis of strings, important for the detection in tweets
require(dplyr) #data management
require(lubridate) #data dates management
require(zoo) #for lagging
require(jtools) #tables
require(huxtable) #tables
require(lmtest) #reg tests
require(vroom) #for loading data

getwd()
#setwd("...") -> set wd at base repo folder

#load helper functions
source(here("helperfunctions/data_loaders.R"))
source(here("helperfunctions/date_selector.R"))
source(here("helperfunctions/plotters.R"))
source(here("helperfunctions/quick_arma.R"))
source(here("helperfunctions/r.vol_calculators.R"))

#load data
#STOXX 50
data_loader(symbol="VGK")

```

# Price
Here we provide some descriptive facts about our financial data on VGK prices.

## Plots
```{r total market plots, warning=FALSE, message=FALSE}

#All Time
price_plotter(raw_VGK,"VGK Price Over Time")
  

#2024
VGK_2024 = year_selector(raw_VGK,2024)
price_plotter_year(VGK_2024,"VGK Price - 2024")


#April 2025
VGK_2025_04 = month_selector(raw_VGK,2024,04)
price_plotter_month(VGK_2025_04,"VGK Price - April 2025")


#9th of April 2025
VGK_2025_04_09 = day_selector(raw_VGK,2024,04,09)
price_plotter_day(VGK_2025_04_09,"VGK Price - 9th of April 2025")


```


## Time Series Analysis
This is not at all related to our final analysis. It is just in order to see
the financial data on its own and how it behaves as a time series.
```{r time series, warning=FALSE, message=FALSE}

acf(VGK_2025_04_09$close)
pacf(VGK_2025_04_09$close)

AR1 = arima(VGK_2025_04_09$close,c(1,0,0),method="ML")
AR2 = arima(VGK_2025_04_09$close,c(2,0,0),method="ML")
AR3 = arima(VGK_2025_04_09$close,c(3,0,0),method="CSS")
table1 = export_summs(AR1,AR2,AR3, model.names = c("AR1","AR2","AR3"), digits = 4)
huxtable::caption(table1) <- "AR Estimations"
huxtable::set_width(table1, 0.8)

AR1res = as.numeric(AR1$residuals)
AR1res_lagged <- lag(AR1res, 1)
iidcheck1 = lm(AR1res ~ AR1res_lagged)
AR2res = as.numeric(AR2$residuals)
AR2res_lagged <- lag(AR2res, 1)
iidcheck2 = lm(AR2res ~ AR2res_lagged)
AR3res = as.numeric(AR3$residuals)
AR3res_lagged <- lag(AR3res, 1)
iidcheck3 = lm(AR3res ~ AR3res_lagged)
table2 = export_summs(iidcheck1,iidcheck2,iidcheck3, 
             model.names = c("AR1 Residuals","AR2 Residuals","AR3 Residuals"), 
             digits = 4)
huxtable::caption(table2) <- "Checking Residuals"
huxtable::set_width(table2, 0.8)

```



\newpage

# Realised Volatility

## Computations
```{r volatility compute, warning=FALSE, message=FALSE}

#avg per day for each month of any dataset
vol_VGK_daily = r.vol_daily(raw_VGK,merge=F)
head(vol_VGK_daily)

#can then filter out years, months, or days
vol_24d = year_selector(vol_VGK_daily,2024)
vol_24_08d = month_selector(vol_VGK_daily,2024,08)
vol_24_11_04d = day_selector(vol_VGK_daily,2024,11,04) #scalar


#avg per hour for each day of each month of any dataset
vol_VGK_hourly = r.vol_hourly(raw_VGK,merge=F)
head(vol_VGK_hourly)

#can then filter out years, months, or days
vol_24h = year_selector(vol_VGK_hourly,2024)
vol_24_08h = month_selector(vol_VGK_hourly,2024,08)
vol_24_11_04h = day_selector(vol_VGK_hourly,2024,11,04) #vector

```


## Plots
```{r volatility plots, warning=FALSE, message=FALSE}

#avg per day volatility all time
dvol_plotter(vol_VGK_daily,breaks="yearly",
             title="VGK Volatility Over Time")

#avg per day volatility in a year
dvol_plotter(vol_24d,breaks="monthly",
             title="Realised Volatility - VGK 2024")

#avg per day volatility in a month
dvol_plotter(vol_24_08d,breaks="daily",
             title="Realised Volatility - VGK August 2024")


#hourly volatility all time
hvol_plotter(vol_VGK_hourly,breaks="yearly",
             title="VGK Volatility Over Time")

#hourly volatility in a year
hvol_plotter(vol_24h,breaks="monthly",
             title="Realised Volatility - VGK 2024")

#hourly volatility in a month
hvol_plotter(vol_24_08h,breaks="daily",
             title="Realised Volatility - VGK August 2024")

#hourly volatility in a day
hvol_plotter(vol_24_11_04h,breaks="hourly",
             title="Realised Volatility - VGK 4th of November 2024")

```








