---
title: "temp marcos functions"
output:
  pdf_document: 
    toc: true
    fig_caption: yes
header-includes:
  - \usepackage{amsmath}
---
\newpage

```{r library_setup, results=FALSE, warning=FALSE, message=FALSE, echo=FALSE}
rm(list=ls())
require(tinytex) #LaTeX
require(ggplot2) #plots
require(AEC) #JP-Renne functions
require(expm) #matrix exponents
require(here) #directory finder
require(stringr) # analysis of strings, important for the detection in tweets
require(dplyr) #data management
require(lubridate) #data dates management
require(zoo) #for lagging
require(jtools) #tables
require(lmtest) #reg tests

getwd()
#setwd("...") -> set wd at base repo folder
```

# Data 

## Raw Data
```{r rawdata_setup, results=FALSE, warning=FALSE, message=FALSE}

#political shocks
raw_truths <- read.csv(here("data/political_data", "trump_all_truths.csv"))
raw_tweets <- read.csv(here("data/political_data", "tweets.csv"))


#market prices
raw_ONEQ <- read.csv(here("data/market_data", "ONEQ.csv"))
raw_SMI <- read.csv(here("data/market_data", "SMI.csv"))
raw_SPY <- read.csv(here("data/market_data", "SPY.csv")) 
raw_VTHR <- read.csv(here("data/market_data", "VTHR.csv"))
raw_VTI <- read.csv(here("data/market_data", "VTI.csv"))
raw_VGK <- read.csv(here("data/market_data", "VGK.csv"))
raw_DAX <- read.csv(here("data/market_data", "DAX.csv"))
raw_ASHR <- read.csv(here("data/market_data", "ASHR.csv"))

raw_SPYy <- read.csv(here("data/market_data", "Spyqyahoo.csv")) #yahoo

```


```{r data looper}
data_loop = function(year,symbol){ #symbol must be a string
  year = paste(year)
  months = c("01","02","03","04","05","06","07","08","09","10","11","12")
  for (t in 1:length(months)) {
    date = paste(year, months[t], sep="-")
    data = av_get(symbol, av_fun="TIME_SERIES_INTRADAY",interval="1min",
                  adjusted="false", extended_hours="false",
                  month=date, outputsize="full")
filename = paste(symbol,date,sep="-")
filename = paste("~/", filename, sep="")
filename = paste(filename,".csv",sep="")
write.csv(data,filename)
}}
```

```{r data loader}
data_loader = function(year,months,symbol){
  year = paste(year)
  months = sprintf("%02d",months)
  for (t in 1:length(months)) {
    date = paste(year, months[t], sep="-")
    dataname = paste(symbol,date,sep="-")
    filename = paste(dataname,".csv",sep="")
    assign(paste("raw",dataname,sep="_"),
           read.csv(here("data/market_data", filename)), envir = .GlobalEnv)
  }}

#example: data_loader(year=2021,months=1:6,symbol="SPY")

```

```{r}
data_loader <- function(year, symbol) {
  # Predefine the list of months (static months)
  #months <- c("01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12")
  months = c("01","02","03","04","05","06")
  # Loop through each month
  for (t in 1:length(months)) {
    # Construct the date string
    date <- paste(year, months[t], sep = "-")
    
    # Create the dataname and filename
    dataname <- paste(symbol, date, sep = "-")
    filename <- paste(dataname, ".csv", sep = "")
    
    # Read the CSV file
    data <- read.csv(here("data/market_data", filename))
    
    # Assign the data to a dynamically generated variable
    assign(paste("raw", dataname, sep = "_"), data, envir = .GlobalEnv)
  }
}
data_loader(2021,"SPY")
```




```{r day_selector}
day_selector <- function(rawdata,year,month,day){
     date = paste("^",year,"-",sprintf("%02d",month),"-",sprintf("%02d",day),sep="")
     newdata = filter(rawdata, str_detect(timestamp, date))
     newdata$timestamp = as.POSIXct(newdata$timestamp, 
                                    format = "%Y-%m-%d %H:%M:%S", tz = "EST")
     return(newdata)
}

#day_ONEQ_0409 = day_selector(raw_ONEQ,2025,04,09) #usage
```

```{r plotter}

day_plotter = function(data,title){
  ggplot(data, aes(x = timestamp, y = close)) +
  geom_point(color = "blue", size = 0.01) +
  geom_line(aes(group=1)) +
  labs(title = title,
       x = "Time",
       y = "Close Price") +
   scale_x_datetime(date_labels = "%H:%M",  
                    date_breaks = "60 min") +
   theme_minimal() +
   theme(axis.text.x = element_text(angle = 45, hjust = 1))
}

#day_plotter(day_ONEQ_0409,"ONEQ Price on April 9th") #usage
```


```{r quick time series analysis}

quick_arma = function(daydata,p,d,q){ #p,d,q as in arima
  acf(daydata$close)
  pacf(daydata$close)
  names = c(paste("AR",p,sep="-"),paste("AR",(p+1),sep="-"),paste("AR",(p+2),sep="-"))

  AR1 = arima(daydata$close,c(p,d,q),method="ML")
  AR2 = arima(daydata$close,c((p+1),d,q),method="ML")
  AR3 = arima(daydata$close,c((p+2),d,q),method="ML")
  table1 = export_summs(AR1,AR2,AR3, model.names = names, digits = 4)
  huxtable::caption(table1) <- "AR Estimations"
  huxtable::set_width(table1, 0.8)

  names2 = paste(names,"Residuals")
  AR1res = as.numeric(AR1$residuals)
  REG1res_lagged <- lag(AR1res, 1)
  iidcheck1 = lm(AR1res ~ REG1res_lagged)
  AR2res = as.numeric(AR2$residuals)
  REG2res_lagged <- lag(AR2res, 1)
  iidcheck2 = lm(AR2res ~ REG2res_lagged)
  AR3res = as.numeric(AR3$residuals)
  REG3res_lagged <- lag(AR3res, 1)
  iidcheck3 = lm(AR3res ~ REG3res_lagged)
  table2 = export_summs(iidcheck1,iidcheck2,iidcheck3, 
                        model.names = names2, digits = 4)
  huxtable::caption(table2) <- "Checking Residuals"
  huxtable::set_width(table2, 0.8)

  return(list(table1,table2))

}


#quick_arma(day_ONEQ_0409,2,0,0) #usage
```

```{r realised volatility for one day}

#t data is t=day's data
r.vol = function(t_data){
  p_t = t_data$close
  p_t_1 <- lag(p_t, 1)
  delta_price = p_t_1 - p_t
  delta_price_sqr = delta_price^2
  v_t = sum(na.omit(delta_price_sqr)) / length(na.omit(delta_price))
  return(v_t)
}

```



```{r realised volatility vector for a month}

#data as a month's csv file 
r.vol_month = function(data){
  days = unique(format(as.Date(data$timestamp, #find all days excluding weekends etc
                        format = "%Y-%m-%d %H:%M:%S"),format="%d"))
  month = unique(format(as.Date(data$timestamp, #for day selector
                      format = "%Y-%m-%d %H:%M:%S"),format="%m"))
  month = as.numeric(month) #due to how day selector input is defined
  year = unique(format(as.Date(data$timestamp, #for day selector
                      format = "%Y-%m-%d %H:%M:%S"),format="%Y"))
  year = as.numeric(year)
  r_vol = c(1:length(days)) #preparing solution vector
  
  for (i in 1:length(days)){ #loop for each day
    daydata = day_selector(data,year,month,as.numeric(days[i])) #selects data for each day
    r_vol[i] = r.vol(daydata) #computes realized volatility for each day
  }
  return(r_vol)
}

#e.g. r.vol_month(raw_SPY2021_01)
```

```{r realised volatility for hours in one day}

#t data is t=day data
r.vol_hour = function(t_data){
  hours = unique(format(as.POSIXct(t_data$timestamp, 
                        format = "%Y-%m-%d %H:%M:%S"),format="%H"))
  day = unique(format(as.Date(t_data$timestamp, 
                        format = "%Y-%m-%d %H:%M:%S"),format="%d"))
  month = unique(format(as.Date(t_data$timestamp, 
                      format = "%Y-%m-%d %H:%M:%S"),format="%m"))
  year = unique(format(as.Date(t_data$timestamp, 
                      format = "%Y-%m-%d %H:%M:%S"),format="%Y"))
  r_vol = c(1:length(hours)) #preparing solution vector
  for (i in 1:length(hours)){
    date = paste(year,month,day,sep="-")
    date = paste(date,hours[i])
    newdata = filter(t_data, str_detect(timestamp, date))
    p_h = newdata$close
    p_h_1 <- lag(p_h, 1)
    delta_price = p_h_1 - p_h
    delta_price_sqr = delta_price^2
    v_h = sum(na.omit(delta_price_sqr)) / length(na.omit(delta_price)) #avg per hour
    r_vol[i] = v_h
  }
  return(r_vol)
}

#example: r.vol_hour(day_SPY_0402)

```




```{r plot this volatility}

```




