# Introduction 

Write text here bla bla bla

## Literature Review

Information is one of the most valuable assets in the financial market. Its importance
lies at the core of the “Perfect Market Hypothesis” (PMH), which states that the prices 
of assets fully reflect all available information, adjusting immediately to any new data 
(2), and thereby creating a strong demand for information flow. In addition, the “Mixture 
of Distribution Hypothesis” states that the release of new information is closely linked 
to mouvements in both realized and implied volatility (1)(3)(7). Consequently, a large 
part of the literature had focused on the relation between announcements, news and 
market activity. For example, Schumaker and Shen (4) use various linguistic and 
textual representations derived from financial news to predict stock market prices. 
Similarly, Ederington and Lee (5) analyze the impact of macroeconomic news 
announcements on interest rate and foreign exchange futures markets, particularly in 
terms of price changes and volatility. Both studies, among others, find that prices—
 such as stock prices—react primarily within minutes after the release of new 
information (4)(5). 
Recently, the world has witnessed the rise of the Internet which revolutionized the 
dissemination and accessibility of information. Social media enable investors, analysts 
or politicians to instantly share their information, news or opinions. This led some 
studies to focus on the communication dynamics of social platform to predict changes 
in the returns of financial assets (6)(8). In this context, the impact of Trump’s tweets on 
various financial and macroeconomic variables has been analysed by several studies, 
especially during his first mandate. Using high-frequency financial data, Gjerstad et al. 
(y) found an increase in uncertainty and trading volume, along with a decline in the 
U.S. stock market—regardless of the tweet's content. However, the effect was stronger 
when Trump used confrontational words such as "tariff" or "trade war." Some of his 
announcements also influenced the U.S. dollar exchange rate (l) and certain market 
indices within minutes of the tweet being posted (r)(a). Other scholars have shown that 
negative Trump’s tweets about specific companies tended to reduce demand for their 
stocks (b)(g), whereas some other have shown that they also impact market volatility 
indices such as the VIX (w) or the Volfele(v). The effects of his tweets also extended 
beyond the U.S.. For example, Sun and al. shows a positive relationship between 
volatility in European stock markets and tweeter activity of Trump, and this effect tends 
to intensify as public intention for his tweet grows (z).