---
bibliography: macroeconometrics_citations.bib  #
csl: apa.csl
link-citations: true
editor_options: 
  markdown: 
    wrap: 72
---

# Data

## Stock Data

Since we do not have access to high frequency data on Stock Indices directly, we
use ETF's that approximate these indices. We downloaded one-minute invervall data
on multiple Indices, notably the S&P 500 ETF with the Ticker SPY from Alphavantage.
Then we calculated hourly volatility for these indices. Since trading starts at
09:30 the interval from 09:00 to 10:00 only includes half an hour of actual trading.

The formula for hourly volatility is... 2

## Political Data

We source Trumps Posts from two places. The Tweets are from Kaggle
@DonaldTrumpTweets and go until the 8th of January 2021. Since he
switched his primary Posting platform to Truth Social we use only that
Data from 2021 onwards. All Truth Social Posts were scrapped from
trumpstruth.org, a webpage that aims to conserve all his posts. You can
find the dataset, and webscrapper, and Data cleaning process in the
Appendix.

Since we're using financial data that is constrained by trading hours,
we decided to move posts after 16:00 to the next trading day's opening
hour.[^2]

All tweets then get aggregated on the hour. We then extract a dummy if he posted
in the hour, how many times he posted and how many times he mentioned certain words.

Further we applied some simple sentiment analysis algorithms on the data to see
if there are certain sentiments in his tweets that move the markets. More
information and detailed process are in the appendix and online.

## Final Dataframe

Show here maybe??


[^2]: So a Post on friday 18:00 would be moved to Monday 09:00
