# Conclusion


We started this project with the intention of understanding whether the impact of Trump’s social media posts affect financial markets, and to see if there is perhaps a difference from his first presidential mandate. After various headaches with our data, we first ran ARMA-X models where we found significant and positive results albeit with strong auto-correlation in the errors, with only the second term analysis offering more convincing results. We then tried SVAR models for a possibly more accurate picture, though with little to no success. We once again saw strong auto-correlation in the errors, which we accounted for by using Newey-West standard errors. We found that the only significant coefficients are actually negative, suggesting Trump’s social media presence would actually \textit{reduce} volatility. There is, however, a consistent pattern in the signs and magnitude of the SVAR coefficients (particularly for $Tariff$ \& $China$)
and the fact that the standard errors are large may reflect a lack of precision in 
the selection of the shocks. It might well be that there are two types of social media posts:
information and noise. That is to say, certain posts may be completely disregarded by investors
as, for instance, emotional outbursts, personal attacks, or other financially irrelevant
remarks, while others would be treated as official policy statements with concrete
consequences to the economy. If this were to be the case, our coefficients would be 
biased downwards, underestimating the impact of the \textit{relevant} posts and would explain 
the high standard errors. A way to counteract this could be to find a way to filter 
the social media posts dataset for only the financially relevant shocks, possibly 
by using more sophisticated sentiment analysis.

Altogether, we would strongly suggest against trying to interpret these results given that the models seem to not fit particularly well. This may be due to seasonality in our data (a common trend seen in our daily AVH being high volatility in the first open hours, and a gradual slowdown for the rest of the day), or to our handling of non-market hours. Further work could look at exploring said issues in greater depth, further complicate the models by adding more variables and interactions between them, and/or additionally use more sophisticated models with very large lag counts. 
