# Appendix



## Table 1
 
 
\begin{table}
\caption{ARMAX Models of Average Hourly Volatility}
\begin{center}
\begin{tabular}{l c c c c c}
\hline
 & Model 1 & Model 2 & Model 3 & Model 4 & Model 5 \\
\hline
AR(1)              & $0.0300$        & $0.0278$        & $0.2200^{***}$  & $2.1903^{***}$  & $0.2209^{***}$  \\
                   & $(0.0510)$      & $(0.0510)$      & $(0.0084)$      & $(0.0096)$      & $(0.0084)$      \\
AR(2)              & $0.7229^{***}$  & $0.7210^{***}$  & $0.9388^{***}$  & $-1.4727^{***}$ & $0.9382^{***}$  \\
                   & $(0.0397)$      & $(0.0399)$      & $(0.0037)$      & $(0.0173)$      & $(0.0037)$      \\
AR(3)              & $0.2110^{***}$  & $0.2148^{***}$  & $-0.1837^{***}$ & $0.2784^{***}$  & $-0.1837^{***}$ \\
                   & $(0.0287)$      & $(0.0284)$      & $(0.0079)$      & $(0.0082)$      & $(0.0079)$      \\
MA(1)              & $0.2751^{***}$  & $0.2779^{***}$  & $0.0870^{***}$  & $-1.8955^{***}$ & $0.0878^{***}$  \\
                   & $(0.0496)$      & $(0.0496)$      & $(0.0042)$      & $(0.0062)$      & $(0.0042)$      \\
MA(2)              & $-0.6445^{***}$ & $-0.6430^{***}$ & $-0.8960^{***}$ & $0.9165^{***}$  & $-0.8950^{***}$ \\
                   & $(0.0284)$      & $(0.0285)$      & $(0.0042)$      & $(0.0063)$      & $(0.0042)$      \\
MA(3)              & $-0.3527^{***}$ & $-0.3563^{***}$ &                 &                 &                 \\
                   & $(0.0256)$      & $(0.0253)$      &                 &                 &                 \\
$TweetDummy_{t}$   & $0.0014^{***}$  &                 &                 &                 &                 \\
                   & $(0.0002)$      &                 &                 &                 &                 \\
$TweetDummy_{t-1}$ & $0.0008^{***}$  &                 &                 &                 &                 \\
                   & $(0.0002)$      &                 &                 &                 &                 \\
$TweetCount_{t}$   &                 & $0.0004^{***}$  &                 &                 &                 \\
                   &                 & $(0.0001)$      &                 &                 &                 \\
$TweetCount_{t-1}$ &                 & $0.0002^{**}$   &                 &                 &                 \\
                   &                 & $(0.0001)$      &                 &                 &                 \\
$Tariff_{t}$       &                 &                 & $0.0035^{*}$    &                 &                 \\
                   &                 &                 & $(0.0014)$      &                 &                 \\
$Tariff_{t-1}$     &                 &                 & $0.0191^{***}$  &                 &                 \\
                   &                 &                 & $(0.0015)$      &                 &                 \\
$Tariff_{t-2}$     &                 &                 & $0.0103^{***}$  &                 &                 \\
                   &                 &                 & $(0.0015)$      &                 &                 \\
$Tariff_{t-3}$     &                 &                 & $-0.0045^{**}$  &                 &                 \\
                   &                 &                 & $(0.0014)$      &                 &                 \\
$Trade_{t}$        &                 &                 &                 & $0.0032$        &                 \\
                   &                 &                 &                 & $(0.0018)$      &                 \\
$Trade_{t-1}$      &                 &                 &                 & $0.0016$        &                 \\
                   &                 &                 &                 & $(0.0018)$      &                 \\
$China_{t}$        &                 &                 &                 &                 & $0.0026^{*}$    \\
                   &                 &                 &                 &                 & $(0.0012)$      \\
\hline
AIC                & $-45761.2161$   & $-45737.6695$   & $-46020.9547$   & $-45816.1540$   & $-45840.5349$   \\
AICc               & $-45761.2051$   & $-45737.6585$   & $-46020.9415$   & $-45816.1449$   & $-45840.5277$   \\
BIC                & $-45682.1963$   & $-45658.6497$   & $-45934.0340$   & $-45745.0361$   & $-45777.3186$   \\
Log Likelihood     & $22890.6081$    & $22878.8348$    & $23021.4774$    & $22917.0770$    & $22928.2675$    \\
Num. obs.          & $19970$         & $19970$         & $19968$         & $19970$         & $19971$         \\
\hline
\multicolumn{6}{l}{\scriptsize{$^{***}p<0.001$; $^{**}p<0.01$; $^{*}p<0.05$}}
\end{tabular}
\label{tab:armax}
\end{center}
\end{table}




## Table 2  


\begin{table}
\caption{Split-Term ARMAX Models of Average Hourly Volatility}
\begin{center}
\begin{tabular}{l c c c c c c}
\hline
 & First Term (1) & First Term (2) & First Term (3) & Second Term (1) & Second Term (2) & Second Term (3) \\
\hline
AR(1)          & $0.2953^{***}$  & $0.2943^{***}$  & $0.2927^{***}$  & $0.9686^{***}$  & $0.9683^{***}$  & $0.9693^{***}$  \\
               & $(0.0225)$      & $(0.0224)$      & $(0.0224)$      & $(0.0163)$      & $(0.0163)$      & $(0.0161)$      \\
AR(2)          & $0.1434^{***}$  & $0.1439^{***}$  & $0.1438^{***}$  &                 &                 &                 \\
               & $(0.0220)$      & $(0.0220)$      & $(0.0219)$      &                 &                 &                 \\
AR(3)          & $0.5456^{***}$  & $0.5462^{***}$  & $0.5480^{***}$  &                 &                 &                 \\
               & $(0.0223)$      & $(0.0222)$      & $(0.0222)$      &                 &                 &                 \\
MA(1)          & $0.1854^{***}$  & $0.1863^{***}$  & $0.1866^{***}$  & $-0.6965^{***}$ & $-0.6905^{***}$ & $-0.7207^{***}$ \\
               & $(0.0180)$      & $(0.0179)$      & $(0.0179)$      & $(0.0469)$      & $(0.0469)$      & $(0.0467)$      \\
MA(2)          & $-0.1707^{***}$ & $-0.1706^{***}$ & $-0.1695^{***}$ & $-0.1732^{***}$ & $-0.1755^{***}$ & $-0.1609^{***}$ \\
               & $(0.0169)$      & $(0.0169)$      & $(0.0168)$      & $(0.0437)$      & $(0.0438)$      & $(0.0434)$      \\
MA(3)          & $-0.6557^{***}$ & $-0.6564^{***}$ & $-0.6575^{***}$ &                 &                 &                 \\
               & $(0.0162)$      & $(0.0161)$      & $(0.0161)$      &                 &                 &                 \\
$Tariff_{t}$   & $0.0011$        &                 &                 & $0.0048$        &                 &                 \\
               & $(0.0010)$      &                 &                 & $(0.0099)$      &                 &                 \\
$Tariff_{t-1}$ &                 &                 &                 & $0.0278^{**}$   &                 &                 \\
               &                 &                 &                 & $(0.0102)$      &                 &                 \\
$Tariff_{t-2}$ &                 &                 &                 & $0.0168$        &                 &                 \\
               &                 &                 &                 & $(0.0099)$      &                 &                 \\
$Trade_{t}$    &                 & $0.0023^{**}$   &                 &                 & $-0.0074$       &                 \\
               &                 & $(0.0009)$      &                 &                 & $(0.0297)$      &                 \\
$China_{t}$    &                 &                 & $0.0018^{**}$   &                 &                 & $0.0173$        \\
               &                 &                 & $(0.0006)$      &                 &                 & $(0.0319)$      \\
$China_{t-1}$  &                 &                 &                 &                 &                 & $0.1515^{***}$  \\
               &                 &                 &                 &                 &                 & $(0.0324)$      \\
$China_{t-2}$  &                 &                 &                 &                 &                 & $0.1309^{***}$  \\
               &                 &                 &                 &                 &                 & $(0.0319)$      \\
\hline
AIC            & $-28604.6559$   & $-28610.2269$   & $-28613.1693$   & $633.4836$      & $638.2093$      & $610.2140$      \\
AICc           & $-28604.6303$   & $-28610.2013$   & $-28613.1437$   & $633.7676$      & $638.3737$      & $610.4980$      \\
BIC            & $-28542.9191$   & $-28548.4901$   & $-28551.4325$   & $667.4525$      & $663.7092$      & $644.1829$      \\
Log Likelihood & $14311.3279$    & $14314.1134$    & $14315.5847$    & $-308.7418$     & $-313.1047$     & $-297.1070$     \\
Num. obs.      & $7042$          & $7042$          & $7042$          & $516$           & $518$           & $516$           \\
\hline
\multicolumn{7}{l}{\scriptsize{$^{***}p<0.001$; $^{**}p<0.01$; $^{*}p<0.05$}}
\end{tabular}
\label{tab:armax_term}
\end{center}
\end{table}




## Table 3

\begin{table}

\caption{Separate Terms Ljung-Box Test p-values}
\centering
\begin{tabular}[t]{l|r}
\hline
Model & Ljung.Box.p.value\\
\hline
First Term Tariffs & 0.0000000\\
\hline
First Term Trade & 0.0000000\\
\hline
First Term China & 0.0000000\\
\hline
Second Term Tariffs & 0.8489828\\
\hline
Second Term Trade & 0.8322070\\
\hline
Second Term China & 0.5122385\\
\hline
\end{tabular}
\end{table}





