---
title: "wordclouds"
output:
  html_document:
    keep_md: true
---


```{r}
# Load libraries
require(tm)
require(wordcloud)
require(SnowballC)
require(RColorBrewer)
require(dplyr)
require(quanteda.textplots)
require(quantmod)
require(alphavantager)
require(quanteda)
require(ggplot2)
require(lubridate)
require(rvest)
require(httr)
require(tidyverse)
require(lubridate)
require(xml2)
suppressMessages(require(here))
```



```{r}
tweets <- read.csv(here("data/political_data", "tweets.csv"))

#Only keep original Tweets
tweets <- tweets %>% filter(isRetweet != "t")
tokens <- tokens(tweets$text)
dfm <- dfm(tokens)
```



```{r}
corpus_tweets <- corpus(tweets$text)
```

```{r}
additional_words <- c("@realdonaldtrump")
all_stopwords <- c(stopwords("en"), additional_words)
```



```{r}
tokens_tweets <- tokens(corpus_tweets,  
                        remove_punct = TRUE, 
                        remove_numbers = TRUE)

tokens_tweets <- tokens_remove(tokens_tweets, all_stopwords)  # Remove stopwords
```


```{r}
dfm_tweets <- dfm(tokens_tweets)
```

```{r}
textplot_wordcloud(dfm_tweets, min_count = 5, color = RColorBrewer::brewer.pal(8, "Dark2"))
```


