---
title: "ARMA-X Analysis Tutorial"
output:
  pdf_document: 
    toc: true
    fig_caption: yes
    latex_engine: lualatex
header-includes:
  - \usepackage{amsmath}
---
\newpage

```{r library_setup, results=FALSE, warning=FALSE, message=FALSE, echo=FALSE}
rm(list=ls())
require(tinytex) #LaTeX
require(ggplot2) #plots
require(AEC) #JP-Renne functions
require(AER) #NW formula
require(forecast) #time series stuff
require(expm) #matrix exponents
require(here) #directory finder
require(stringr) # analysis of strings, important for the detection in tweets
require(dplyr) #data management
require(lubridate) #data dates management
require(zoo) #for lagging
require(jtools) #tables
require(huxtable) #tables
require(lmtest) #reg tests
require(vroom) #for loading data
require(data.table) #for data filtering
require(sysid) #for ARMA-X modeling
require(sandwich) #regression errors
require(stargazer) #nice reg tables
require(tidytext) #text mining
require(textstem) #lemmatization
require(quanteda) #tokenization
require(texreg) #arima tables

getwd()
#setwd("...") -> set wd at base repo folder

#load helper functions
source(here("helperfunctions/data_loaders.R"))
source(here("helperfunctions/date_selector.R"))
source(here("helperfunctions/plotters.R"))
source(here("helperfunctions/quick_arma.R"))
source(here("helperfunctions/r.vol_calculators.R"))
source(here("helperfunctions/truths_cleaning_function.R"))
source(here("helperfunctions/armax_functions.R"))
```


# Data 


## Load Base Data

```{r data_setup, results=FALSE, warning=FALSE, message=FALSE}

# 1. Load Political Social Media

#contains posts from Twitter & TruthSocial
social <- read.csv(here("data/mothership", "social.csv"))

social_hourly <- read.csv(here("data/mothership", "socialhourly.csv"))


# 2. Load Financial

#S&P500
SPY <- read.csv(here("data/mothership", "SPY.csv"))

#STOXX50
VGK <- read.csv(here("data/mothership", "VGK.csv"))

#CSI 300 (China)
ASHR <- read.csv(here("data/mothership", "ASHR.CSV"))

```

```{r data_time, results=FALSE, warning=FALSE, message=FALSE}

#make posixct
SPY$timestamp = as.POSIXct(SPY$timestamp,format = "%Y-%m-%d %H:%M:%S")
VGK$timestamp = as.POSIXct(VGK$timestamp,format = "%Y-%m-%d %H:%M:%S")
ASHR$timestamp = as.POSIXct(ASHR$timestamp,format = "%Y-%m-%d %H:%M:%S")
social$timestamp = as.POSIXct(social$timestamp,format = "%Y-%m-%d %H:%M:%S")
social_hourly$timestamp = as.POSIXct(social_hourly$timestamp,format = "%Y-%m-%d %H:%M:%S")
social_hourly$adjusted_time = as.POSIXct(social_hourly$adjusted_time,format = "%Y-%m-%d %H:%M:%S")

#select timeframe 
SPY = filter(SPY,between(timestamp, as.Date('2018-01-01'), as.Date('2025-05-07')))
VGK = filter(VGK,between(timestamp, as.Date('2018-01-01'), as.Date('2025-05-07')))
ASHR = filter(ASHR,between(timestamp, as.Date('2018-01-01'), as.Date('2025-05-07')))
social = filter(social,between(timestamp, as.Date('2018-01-01'), as.Date('2025-05-07')))
social_hourly = filter(social_hourly,between(timestamp, as.Date('2018-01-01'), as.Date('2025-05-07')))

```



## Volatility
```{r SPY volatility}

#find hourly volatility
SPY_volatility = dplyr::select(SPY,timestamp,r_vol_h)

#aggregating per hour
SPY_volatility = SPY_volatility %>%
          mutate(timestamp = floor_date(timestamp, unit = "hour")) %>%
          distinct(timestamp, .keep_all = TRUE) 

#plot
hvol_plotter(SPY_volatility,breaks="3 month", 
             title="Realised Volatility - SPY")
```

```{r VGK volatility}

#find hourly volatility
VGK_volatility = dplyr::select(VGK,timestamp,r_vol_h)

#aggregating per hour
VGK_volatility = VGK_volatility %>%
          mutate(timestamp = floor_date(timestamp, unit = "hour")) %>%
          distinct(timestamp, .keep_all = TRUE) 

```

```{r ASHR volatility}

#find hourly volatility
ASHR_volatility = dplyr::select(ASHR,timestamp,r_vol_h)

#aggregating per hour
ASHR_volatility = ASHR_volatility %>%
          mutate(timestamp = floor_date(timestamp, unit = "hour")) %>%
          distinct(timestamp, .keep_all = TRUE) 

```

## Number of Posts 
```{r social media count}

#find count
tweetcount = dplyr::select(social_hourly,timestamp,adjusted_time,N)

#for taking count of closed market hours
tweetcount2 <- tweetcount %>%
  group_by(adjusted_time) %>%
  summarise(N = sum(N)) 

#plot
ggplot(tweetcount, aes(x = timestamp, y = N)) +
    geom_point(color = "#253494", size = 1) +
    scale_x_datetime(date_labels = "%b %Y", date_breaks = "3 month") +
    labs(title = "Trump Social Media Count",
         x = NULL,
         y = "number of tweets/truths") +
    theme_minimal(base_size = 14) +
    theme(axis.text.x = element_text(angle = 45, hjust = 1),
          plot.title = element_text(face = "bold", hjust = 0.5))
```

## Dummy for Social Media Post
```{r dummy}

#find dummy
tweetdummy = dplyr::select(social_hourly,timestamp,adjusted_time,dummy)

#for taking count of closed market hours
tweetdummy2 <- tweetdummy %>%
  group_by(adjusted_time) %>%
  summarise(dummy = sum(dummy)) 
#peculiar interpretation for dummy: if dummy>1 it means that there were x
#out-hours which had tweets in them

```

## Number of Tweets Mentioning Tariffs 
```{r tariff}

#find count
tariff = dplyr::select(social_hourly,timestamp,adjusted_time,total_tariff)

#for taking count of closed market hours
tariff2 <- tariff %>%
  group_by(adjusted_time) %>%
  summarise(total_tariff = sum(total_tariff)) 

```

## Number of Tweets Mentioning Trade 
```{r trade}

#find count
trade = dplyr::select(social_hourly,timestamp,adjusted_time,total_trade)

#for taking count of closed market hours
trade2 <- trade %>%
  group_by(adjusted_time) %>%
  summarise(total_trade = sum(total_trade)) 


```

## Number of Tweets Mentioning China 
```{r china}

#find count
china = dplyr::select(social_hourly,timestamp,adjusted_time,total_china)

#for taking count of closed market hours
china2 <- china %>%
  group_by(adjusted_time) %>%
  summarise(total_china = sum(total_china)) 

```

## Proportion of Positive 
```{r positive}

#find count
positive = dplyr::select(social_hourly,timestamp,adjusted_time,prop_positive)

#how to count outside hours? since proportion?

```

## Proportion of Negative 
```{r negative}

#find count
negative = dplyr::select(social_hourly,timestamp,adjusted_time,prop_negative)

```


## Merge
```{r armadata merge}

#merge our dependant and independant vars

#case 1: ignore tweets outside trading hours
armax_data = left_join(SPY_volatility, VGK_volatility, by="timestamp")
armax_data = left_join(armax_data, ASHR_volatility, by="timestamp")
armax_data = left_join(armax_data, select(tweetdummy, -adjusted_time), by="timestamp")
armax_data = left_join(armax_data, select(tweetcount, -adjusted_time), by="timestamp")
armax_data = left_join(armax_data, select(tariff, -adjusted_time), by="timestamp")
armax_data = left_join(armax_data, select(trade, -adjusted_time), by="timestamp")
armax_data = left_join(armax_data, select(china, -adjusted_time), by="timestamp")
armax_data = left_join(armax_data, select(positive, -adjusted_time), by="timestamp")
armax_data = left_join(armax_data, select(negative, -adjusted_time), by="timestamp")

rm(armax_data)
#case 2: push tweets made outside market hours to the next open hour
armax_data = left_join(SPY_volatility, VGK_volatility, by="timestamp")
armax_data = left_join(armax_data, ASHR_volatility, by="timestamp")
armax_data <- armax_data %>%
  left_join(tweetdummy2, by = c("timestamp" = "adjusted_time")) 
armax_data <- armax_data %>%
  left_join(tweetcount2, by = c("timestamp" = "adjusted_time")) 
armax_data <- armax_data %>%
  left_join(tariff2, by = c("timestamp" = "adjusted_time")) 
armax_data <- armax_data %>%
  left_join(trade2, by = c("timestamp" = "adjusted_time")) 
armax_data <- armax_data %>%
  left_join(china2, by = c("timestamp" = "adjusted_time")) 

#rename volatility columns
names(armax_data)[2] <- "SPY_vol"
names(armax_data)[3] <- "VGK_vol"
names(armax_data)[4] <- "ASHR_vol"

#convert NA to zeroes
armax_data$N[is.na(armax_data$N)] = 0
armax_data$dummy[is.na(armax_data$dummy)] = 0
armax_data$total_tariff[is.na(armax_data$total_tariff)] = 0
armax_data$total_trade[is.na(armax_data$total_trade)] = 0
armax_data$total_china[is.na(armax_data$total_china)] = 0
#armax_data$prop_positive[is.na(armax_data$prop_positive)] = 0
#armax_data$prop_negative[is.na(armax_data$prop_negative)] = 0

```



# S\&P500 Univariate ARMA-X Models

## Tweet Dummy as Exogenous
```{r armax dummy, results="asis", warning=F, message=F}

#auto.armax selects the lowest AIC value given r (exogenous variable lags) 
res1 = auto.armax(armax_data$SPY_vol,xreg=armax_data$dummy,nb.lags=6,
                latex=F,max.p = 6, max.q = 6, max.d=0)

#armax enables a custom armax specification with p,q,r 
res2 = armax(armax_data$SPY_vol, xreg=armax_data$dummy, nb.lags=2,
                   p=5, q=0, d=0, latex=F)

#auto.armax.r selects the lowest AIC checking all 3 p,q,r values
res3 = auto.armax.r(armax_data$SPY_vol, x=armax_data$dummy, 
                max_p = 6, max_q = 6, max_r = 6, criterion = "AIC", latex=F)

#we want to plot the IRFs of these models
nb.periods = 20

irf.plot(res1,nb.periods)
irf.plot(res2,nb.periods)
irf.plot(res3$model,nb.periods)

```


## Tweet Count as Exogenous
```{r armax count, results="asis", warning=F, message=F}

#auto.armax selects the lowest AIC value given r (exogenous variable lags) 
res1 = auto.armax(armax_data$SPY_vol,xreg=armax_data$N,nb.lags=6,
                latex=F,max.p = 6, max.q = 6, max.d=0)

#armax enables a custom armax specification with p,q,r 
res2 = armax(armax_data$SPY_vol, xreg=armax_data$N, nb.lags=2,
                   p=5, q=0, d=0, latex=F)

#auto.armax.r selects the lowest AIC checking all 3 p,q,r values
res3 = auto.armax.r(armax_data$SPY_vol, x=armax_data$N, 
                max_p = 6, max_q = 6, max_r = 6, criterion = "AIC", latex=F)

#we want to plot the IRFs of these models
nb.periods = 20

irf.plot(res1,nb.periods)
irf.plot(res2,nb.periods)
irf.plot(res3$model,nb.periods)

```


## Tariff as Exogenous
```{r armax tariff, results="asis", warning=F, message=F}

#auto.armax selects the lowest AIC value given r (exogenous variable lags) 
res1 = auto.armax(armax_data$SPY_vol,xreg=armax_data$total_tariff,nb.lags=2,
                latex=F,max.p = 6, max.q = 6, max.d=0)

#armax enables a custom armax specification with p,q,r 
res2 = armax(armax_data$SPY_vol, xreg=armax_data$total_tariff, nb.lags=2,
                   p=6, q=0, d=0, latex=F)

#auto.armax.r selects the lowest AIC checking all 3 p,q,r values
res3 = auto.armax.r(armax_data$SPY_vol, x=armax_data$total_tariff, 
                max_p = 6, max_q = 6, max_r = 6, criterion = "AIC", latex=F)

#we want to plot the IRFs of these models
nb.periods = 20

irf.plot(res1,nb.periods)
irf.plot(res2,nb.periods)
irf.plot(res3$model,nb.periods)

```








```{r dummytariff, eval=FALSE, include=FALSE}

#create X matrix with both exogenous regressors
X = cbind(armax_data$total_tariff,armax_data$N*armax_data$total_tariff)
colnames(X) <- c("Tariff","Tariff*Count")
head(X)

#auto.armax.r selects the lowest AIC checking all 3 p,q,r values
res3 = auto.armax.r(armax_data$SPY_vol, x=X, 
                max_p = 7, max_q = 7, max_r = 3, criterion = "AIC", latex=F)

#we want to plot the IRFs of these models
nb.periods = 20

irf.plot(res3$model,nb.periods)

```






















